#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

fail() {
  echo "FAIL: $1"
  exit 1
}

pass() {
  echo "PASS: $1"
}

expect_fixed() {
  local needle="$1"
  local file="$2"
  local description="$3"
  if grep -Fq "$needle" "$file"; then
    pass "$description"
    return
  fi
  fail "$description (missing: $needle in $file)"
}

expect_absent() {
  local needle="$1"
  local file="$2"
  local description="$3"
  if grep -Fq "$needle" "$file"; then
    fail "$description (unexpected: $needle in $file)"
  fi
  pass "$description"
}

API_CONTROLLER="$PLUGIN_ROOT/src/controllers/ApiController.php"
PLUGIN_FILE="$PLUGIN_ROOT/src/Plugin.php"
DASHBOARD_CONTROLLER="$PLUGIN_ROOT/src/controllers/DashboardController.php"
DASHBOARD_TEMPLATE="$PLUGIN_ROOT/src/templates/dashboard.twig"
CREDENTIALS_TEMPLATE="$PLUGIN_ROOT/src/templates/credentials.twig"
CONTROL_TEMPLATE="$PLUGIN_ROOT/src/templates/control.twig"
SETTINGS_TEMPLATE="$PLUGIN_ROOT/src/templates/settings.twig"
SETTINGS_TAB_TEMPLATE="$PLUGIN_ROOT/src/templates/settings-tab.twig"
SETTINGS_MODEL="$PLUGIN_ROOT/src/models/Settings.php"
ADOPTION_SERVICE="$PLUGIN_ROOT/src/services/AdoptionMetricsService.php"
CONTROL_SERVICE="$PLUGIN_ROOT/src/services/ControlPlaneService.php"
SECURITY_POLICY_SERVICE="$PLUGIN_ROOT/src/services/SecurityPolicyService.php"
READINESS_SERVICE="$PLUGIN_ROOT/src/services/ReadinessService.php"

expect_fixed "public function actionAuthWhoami(): Response" "$API_CONTROLLER" "API exposes auth diagnostics endpoint action"
expect_fixed "public function actionAdoptionMetrics(): Response" "$API_CONTROLLER" "API exposes adoption metrics endpoint action"
expect_fixed "public function actionMetrics(): Response" "$API_CONTROLLER" "API exposes observability metrics endpoint action"
expect_fixed "public function actionConsumersLag(): Response" "$API_CONTROLLER" "API exposes consumer lag endpoint action"
expect_fixed "public function actionConsumersCheckpoint(): Response" "$API_CONTROLLER" "API exposes consumer checkpoint endpoint action"
expect_fixed "protected array|bool|int \$supportsCsrfValidation = false;" "$API_CONTROLLER" "API disables CSRF for machine endpoints"
expect_fixed "private function enforceWriteRequestContract(): ?Response" "$API_CONTROLLER" "API enforces explicit write-request transport contract"
expect_fixed "Write requests must authenticate via Authorization or X-Agents-Token headers." "$API_CONTROLLER" "API rejects query-token auth on write requests"
expect_fixed "Write requests must use Content-Type: application/json." "$API_CONTROLLER" "API requires JSON content type on write requests"
expect_fixed "queryParamAllowedMethods" "$API_CONTROLLER" "Capabilities expose query-token read-only metadata"
expect_fixed "Read-only transport for GET/HEAD requests only when query-token auth is enabled." "$API_CONTROLLER" "OpenAPI documents query-token as read-only"
expect_fixed "defaultTokenScopes()" "$API_CONTROLLER" "API controller derives default scopes from filtered runtime config"
expect_fixed "isCommerceApiEnabled()" "$API_CONTROLLER" "API controller exposes commerce availability guard for public scope catalog"
expect_fixed "commerceScopeKeys()" "$API_CONTROLLER" "API controller defines the commerce scope set for availability filtering"
expect_fixed "governedWriteScopeKeys()" "$API_CONTROLLER" "API controller defines the governed-write scope set for experimental-write filtering"
expect_fixed "'credentialId' => (string)(\$this->authContext['credentialId'] ?? '')" "$API_CONTROLLER" "Sync-state writes receive the authenticated credential id"
expect_fixed "'credentialCount' => (int)(\$this->authContext['credentialCount'] ?? 0)" "$API_CONTROLLER" "Sync-state writes receive the runtime credential count"
expect_fixed "'managedCredentialId' => isset(\$this->authContext['managedCredentialId']) ? (int)\$this->authContext['managedCredentialId'] : null" "$API_CONTROLLER" "Control actor context carries the managed credential id when present"
expect_fixed "private function resolveAuthorizedIntegrationKey" "$PLUGIN_ROOT/src/services/ConsumerLagService.php" "Consumer lag service binds checkpoint writes to the authenticated credential"
expect_fixed "Legacy default token cannot write sync-state when multiple credentials are configured." "$PLUGIN_ROOT/src/services/ConsumerLagService.php" "Consumer lag service blocks ambiguous default-token writes"
expect_fixed '`integrationKey` must match the authenticated credential id' "$PLUGIN_ROOT/src/services/ConsumerLagService.php" "Consumer lag service rejects cross-credential checkpoint writes"

expect_fixed "public function actionControlPolicies(): Response" "$API_CONTROLLER" "API exposes control policies endpoint action"
expect_fixed "public function actionControlPolicyUpsert(): Response" "$API_CONTROLLER" "API exposes control policy upsert endpoint action"
expect_fixed "public function actionControlApprovals(): Response" "$API_CONTROLLER" "API exposes control approvals endpoint action"
expect_fixed "public function actionControlApprovalRequest(): Response" "$API_CONTROLLER" "API exposes control approval request endpoint action"
expect_fixed "public function actionControlApprovalDecide(): Response" "$API_CONTROLLER" "API exposes control approval decide endpoint action"
expect_fixed "public function actionControlExecutions(): Response" "$API_CONTROLLER" "API exposes control executions endpoint action"
expect_fixed "public function actionControlPolicySimulate(): Response" "$API_CONTROLLER" "API exposes control policy simulator endpoint action"
expect_fixed "public function actionControlActionsExecute(): Response" "$API_CONTROLLER" "API exposes control execute endpoint action"
expect_fixed "public function actionControlAudit(): Response" "$API_CONTROLLER" "API exposes control audit endpoint action"

expect_fixed "public function actionWebhookDlqList(): Response" "$API_CONTROLLER" "API exposes webhook DLQ list endpoint action"
expect_fixed "public function actionWebhookDlqReplay(): Response" "$API_CONTROLLER" "API exposes webhook DLQ replay endpoint action"

expect_fixed "'/sync-state/lag'" "$API_CONTROLLER" "OpenAPI/capabilities include sync-state lag path"
expect_fixed "'/sync-state/checkpoint'" "$API_CONTROLLER" "OpenAPI/capabilities include sync-state checkpoint path"
expect_fixed "'/consumers/lag'" "$API_CONTROLLER" "OpenAPI/capabilities include consumers lag path"
expect_fixed "'/consumers/checkpoint'" "$API_CONTROLLER" "OpenAPI/capabilities include consumers checkpoint path"
expect_fixed "'/adoption/metrics'" "$API_CONTROLLER" "OpenAPI/capabilities include adoption metrics path"
expect_fixed "'/metrics'" "$API_CONTROLLER" "OpenAPI/capabilities include observability metrics path"
expect_fixed "'/control/actions/execute'" "$API_CONTROLLER" "OpenAPI/capabilities include control execute path"
expect_fixed "'/webhooks/dlq/replay'" "$API_CONTROLLER" "OpenAPI/capabilities include webhook replay path"
expect_fixed "syncstate:read" "$API_CONTROLLER" "Sync-state read scope is declared in API controller"
expect_fixed "syncstate:write" "$API_CONTROLLER" "Sync-state write scope is declared in API controller"
expect_fixed "adoption:read" "$API_CONTROLLER" "Adoption metrics scope is declared in API controller"
expect_fixed "metrics:read" "$API_CONTROLLER" "Observability metrics scope is declared in API controller"
expect_fixed "control:actions:execute" "$API_CONTROLLER" "Control execution scope is declared in API controller"
expect_fixed "entries:write:draft" "$API_CONTROLLER" "Entry draft write scope is declared in API controller"
expect_fixed "'entries:write' => 'Deprecated alias for \`entries:write:draft\`.'" "$API_CONTROLLER" "Deprecated entry draft scope alias is documented in API controller"
expect_fixed "webhooks:dlq:replay" "$API_CONTROLLER" "Webhook replay scope is declared in API controller"

expect_fixed "'agents/v1/adoption/metrics' => 'agents/api/adoption-metrics'" "$PLUGIN_FILE" "Plugin registers adoption metrics route"
expect_fixed "'agents/v1/metrics' => 'agents/api/metrics'" "$PLUGIN_FILE" "Plugin registers observability metrics route"
expect_fixed "'agents/v1/sync-state/checkpoint' => 'agents/api/consumers-checkpoint'" "$PLUGIN_FILE" "Plugin registers sync-state checkpoint route"
expect_fixed "'agents/v1/sync-state/lag' => 'agents/api/consumers-lag'" "$PLUGIN_FILE" "Plugin registers sync-state lag route"
expect_fixed "'agents/v1/consumers/checkpoint' => 'agents/api/consumers-checkpoint'" "$PLUGIN_FILE" "Plugin registers consumers checkpoint route"
expect_fixed "'agents/v1/consumers/lag' => 'agents/api/consumers-lag'" "$PLUGIN_FILE" "Plugin registers consumers lag route"
expect_fixed "'agents/v1/webhooks/dlq' => 'agents/api/webhook-dlq-list'" "$PLUGIN_FILE" "Plugin registers webhook DLQ list route"
expect_fixed "'agents/v1/webhooks/dlq/replay' => 'agents/api/webhook-dlq-replay'" "$PLUGIN_FILE" "Plugin registers webhook DLQ replay route"
expect_fixed "\$rules['agents/approvals/approvals'] = 'agents/dashboard/control';" "$PLUGIN_FILE" "Plugin registers Control approvals CP route"
expect_fixed "\$rules['agents/approvals/rules'] = 'agents/dashboard/control';" "$PLUGIN_FILE" "Plugin registers Control rules CP route"
expect_fixed "\$rules['agents/approvals/diff'] = 'agents/dashboard/control-diff';" "$PLUGIN_FILE" "Plugin registers Control diff CP route"
expect_fixed "'label' => 'Approvals'" "$PLUGIN_FILE" "Plugin exposes Approvals top-level CP label"
expect_fixed "'label' => 'Accounts'" "$PLUGIN_FILE" "Plugin exposes Accounts top-level CP label"
expect_fixed "buildObservabilitySummary" "$DASHBOARD_CONTROLLER" "Dashboard controller builds observability summary for CP telemetry"
expect_fixed "public function actionClearWebhookTestSink(): Response" "$DASHBOARD_CONTROLLER" "Dashboard controller exposes webhook test sink clear action"
expect_fixed "public function actionSendWebhookTestSinkDelivery(): Response" "$DASHBOARD_CONTROLLER" "Dashboard controller exposes webhook test sink send action"
expect_fixed "public function actionExecuteApprovedControlAction(): Response" "$DASHBOARD_CONTROLLER" "Dashboard controller supports one-click approved execution action"
expect_fixed "public function actionControlDiff(): Response" "$DASHBOARD_CONTROLLER" "Dashboard controller exposes approval diff endpoint"
expect_fixed "'webhookUrlSettingLocked' => (bool)(\$settingsOverrides['webhookUrl'] ?? false)" "$DASHBOARD_CONTROLLER" "Dashboard controller exposes webhook URL lock state to Settings"
expect_fixed "'webhookSecretSettingLocked' => (bool)(\$settingsOverrides['webhookSecret'] ?? false)" "$DASHBOARD_CONTROLLER" "Dashboard controller exposes webhook secret lock state to Settings"
expect_fixed "\$settingsData['webhookUrl'] = \$webhookUrlLocked" "$DASHBOARD_CONTROLLER" "Dashboard controller persists webhook URL from Settings"
expect_fixed "\$settingsData['webhookSecret'] = \$webhookSecretLocked" "$DASHBOARD_CONTROLLER" "Dashboard controller persists webhook secret from Settings"
expect_fixed "approval runs the action immediately when threshold is met" "$DASHBOARD_CONTROLLER" "Dashboard controller enforces execute permission for auto-executing approvals"
expect_fixed "&& strtolower(trim(\$decisionStatus)) === 'approved'" "$DASHBOARD_CONTROLLER" "Dashboard controller auto-executes once final approval threshold is met"
expect_fixed "private function controlTabs(): array" "$DASHBOARD_CONTROLLER" "Dashboard controller defines Control sidebar tabs"
expect_fixed "private function resolveControlTab(): string" "$DASHBOARD_CONTROLLER" "Dashboard controller resolves active Control sidebar tab"
expect_fixed "formatControlActorLabel" "$DASHBOARD_CONTROLLER" "Dashboard controller resolves human-readable control actor labels"
expect_fixed "decidedByLabel" "$DASHBOARD_CONTROLLER" "Dashboard controller decorates approvals with approver labels"
expect_fixed "decorateControlApprovalsWithTargetSets" "$DASHBOARD_CONTROLLER" "Dashboard controller decorates approvals with target-set summaries"
expect_fixed "decorateControlItemsWithActionLabels" "$DASHBOARD_CONTROLLER" "Dashboard controller decorates control items with human-readable action labels"
expect_fixed "buildControlDiffPayload" "$DASHBOARD_CONTROLLER" "Dashboard controller builds normalized approval diff payloads"
expect_fixed "buildControlRedlinePayload" "$DASHBOARD_CONTROLLER" "Dashboard controller builds redline approval diff payloads for text-like fields"
expect_fixed "resolveControlCompletedRevisionComparison" "$DASHBOARD_CONTROLLER" "Dashboard controller can reconstruct completed diff rows from applied revisions"
expect_fixed "resolveControlRevisionDescriptorsByCanonicalId" "$DASHBOARD_CONTROLLER" "Dashboard controller can list applied revision snapshots for completed diff fallback"
expect_fixed "matchControlCompletedRevisionDescriptor" "$DASHBOARD_CONTROLLER" "Dashboard controller can match a completed approval to its applied revision snapshot"
expect_fixed "findControlRevisionForReview" "$DASHBOARD_CONTROLLER" "Dashboard controller can load revision elements for completed diff comparisons"
expect_fixed "\$payload['modeLabel'] = 'Applied revision';" "$DASHBOARD_CONTROLLER" "Dashboard controller labels completed diff fallback as an applied revision compare"
expect_fixed "diffControlRedlineTokens" "$DASHBOARD_CONTROLLER" "Dashboard controller computes inline redline token diffs"
expect_fixed "appendControlDiffRows" "$DASHBOARD_CONTROLLER" "Dashboard controller flattens changed-only diff rows"
expect_fixed "resolveDraftDescriptorByDbLookup" "$DASHBOARD_CONTROLLER" "Dashboard controller can fall back to DB draft resolution when element queries do not hydrate a saved draft"
expect_fixed "getUserByUsernameOrEmail" "$DASHBOARD_CONTROLLER" "Dashboard controller resolves CP users via supported username/email lookup"
expect_fixed "id=\"readinessStateCard\"" "$DASHBOARD_TEMPLATE" "Dashboard readiness view exposes readiness state card"
expect_fixed "agents-status-dashboard-grid" "$DASHBOARD_TEMPLATE" "Dashboard readiness view renders a compact status dashboard grid"
expect_fixed "agents-status-dashboard-card--verdict" "$DASHBOARD_TEMPLATE" "Dashboard readiness view renders a large verdict dashboard card"
expect_fixed "agents-status-dashboard-card__footer" "$DASHBOARD_TEMPLATE" "Dashboard readiness view pins dashboard card actions into a footer row"
expect_fixed "Approvals / Notifications" "$DASHBOARD_TEMPLATE" "Dashboard readiness view exposes the compact approvals and notifications card"
expect_fixed "Target Sets" "$DASHBOARD_TEMPLATE" "Dashboard readiness view exposes the compact target sets card"
expect_fixed "Webhooks" "$DASHBOARD_TEMPLATE" "Dashboard readiness view exposes the compact webhooks card"
expect_fixed "readinessDisplayStateKey" "$DASHBOARD_TEMPLATE" "Dashboard readiness view normalizes the rendered headline state from final summary tones"
expect_fixed "readinessOnlyBootstrapGaps" "$DASHBOARD_TEMPLATE" "Dashboard readiness view derives a setup state from bootstrap-only confidence gaps"
expect_fixed "readinessHasBlockingGate = (not agentsEnabled) or (not readinessDbAvailable)" "$DASHBOARD_TEMPLATE" "Dashboard readiness view does not treat missing credentials as a blocking gate on fresh install"
expect_fixed "'optional' => true" "$READINESS_SERVICE" "Readiness service treats Commerce availability as optional for CMS-only installs"
expect_fixed "if ((bool)(\$criterion['optional'] ?? false)) {" "$READINESS_SERVICE" "Readiness diagnostics skip optional checks when building warnings"
expect_fixed "readinessIntegrationCapacitySummaryLabel = 'Optional'" "$DASHBOARD_TEMPLATE" "Dashboard readiness view treats sync-state as optional until configured"
expect_fixed "No accounts configured yet" "$DASHBOARD_TEMPLATE" "Dashboard readiness view treats missing accounts as setup guidance rather than failure"
expect_fixed "securityBootstrapWarningCodes" "$DASHBOARD_TEMPLATE" "Dashboard readiness view filters bootstrap-only missing-account warnings out of degraded status"
expect_fixed "'code' => 'missing_credentials'" "$SECURITY_POLICY_SERVICE" "Security policy marks missing-account warnings with a stable code for status filtering"
expect_fixed "filterUnavailableDefaultScopes" "$SECURITY_POLICY_SERVICE" "Security policy filters unavailable default scopes before exposing runtime defaults"
expect_fixed "commerceScopeKeys()" "$SECURITY_POLICY_SERVICE" "Security policy defines a commerce scope set for CMS-only installs"
expect_fixed "governedWriteScopeKeys()" "$SECURITY_POLICY_SERVICE" "Security policy defines the governed-write scope set for experimental-write filtering"
expect_fixed "readinessHasMonitoringGap" "$DASHBOARD_TEMPLATE" "Dashboard readiness view distinguishes monitoring gaps from harmless low-traffic observation gaps"
expect_fixed "Confidence signals will strengthen as routine traffic and account activity build over time." "$DASHBOARD_TEMPLATE" "Dashboard readiness view keeps healthy low-traffic environments in a positive ready posture"
expect_fixed "stateLabel: securityCredentialCount == 0 ? 'Optional' : 'Clear'" "$DASHBOARD_TEMPLATE" "Dashboard readiness action mapping suppresses missing-credential setup guidance as an optional signal"
expect_fixed "(row.stateLabel|lower) not in ['clear', 'optional']" "$DASHBOARD_TEMPLATE" "Dashboard readiness action mapping suppresses optional setup signals"
expect_fixed "id=\"readinessActionMappingSection\"" "$DASHBOARD_TEMPLATE" "Dashboard readiness view exposes action mapping section"
expect_fixed "id=\"securitySnapshotSection\"" "$DASHBOARD_TEMPLATE" "Dashboard readiness view preserves security detail section"
expect_fixed "selectedSubnavItem = 'status'" "$DASHBOARD_TEMPLATE" "Dashboard template routes the Status view under the Status subnav"
expect_fixed "id=\"diagnosticsBundleSection\"" "$DASHBOARD_TEMPLATE" "Dashboard readiness view exposes diagnostics bundle section"
expect_fixed "Accounts / Policy" "$DASHBOARD_TEMPLATE" "Dashboard readiness view exposes merged accounts and policy proof section"
expect_fixed "Managed / environment" "$DASHBOARD_TEMPLATE" "Dashboard detail view uses operator-friendly managed/environment account wording"
expect_fixed "Account activity" "$DASHBOARD_TEMPLATE" "Dashboard observability detail uses account activity wording"
expect_fixed "if (!Plugin::getInstance()->isWritesExperimentalEnabled()) {" "$DASHBOARD_CONTROLLER" "Dashboard controller suppresses governed-write approval controls when experimental writes are off"
expect_fixed "\$approval['latestExecution'] = \$latestExecutionByApprovalId[\$approvalId];" "$DASHBOARD_CONTROLLER" "Dashboard controller attaches latest execution before approval decoration"
expect_fixed "latestExecutionResultPayload" "$DASHBOARD_CONTROLLER" "Dashboard controller falls back to latest execution payload when extracting approval target ids"
expect_fixed "boundDraftId" "$DASHBOARD_CONTROLLER" "Dashboard controller falls back to approval-bound draft identity when resolving review targets"
expect_fixed "Traffic / Access" "$DASHBOARD_TEMPLATE" "Dashboard readiness view exposes merged traffic and access proof section"
expect_fixed "id=\"trafficAccessDetailDialog\"" "$DASHBOARD_TEMPLATE" "Dashboard readiness view exposes traffic/access detail dialog"
expect_fixed "data-agents-detail-open=\"trafficAccessDetailDialog\"" "$DASHBOARD_TEMPLATE" "Dashboard readiness view exposes traffic/access detail trigger"
expect_fixed "id=\"deliveryWebhooksDetailDialog\"" "$DASHBOARD_TEMPLATE" "Dashboard readiness view exposes delivery/webhooks detail dialog"
expect_fixed "data-agents-detail-open=\"deliveryWebhooksDetailDialog\"" "$DASHBOARD_TEMPLATE" "Dashboard readiness view exposes delivery/webhooks detail trigger"
expect_fixed "id=\"webhookTestSinkSection\"" "$DASHBOARD_TEMPLATE" "Dashboard readiness view exposes webhook test sink section"
expect_fixed "agents-webhook-test-sink-card" "$DASHBOARD_TEMPLATE" "Dashboard readiness view renders the webhook test sink as a dedicated card"
expect_fixed "Webhook Test Sink" "$DASHBOARD_TEMPLATE" "Dashboard readiness view labels the webhook test sink card"
expect_fixed "writesExperimentalEnabled" "$CREDENTIALS_TEMPLATE" "Accounts template reads governed-write feature state before surfacing picker scopes"
expect_fixed "commercePluginEnabled" "$CREDENTIALS_TEMPLATE" "Accounts template reads commerce availability before surfacing picker scopes"
expect_fixed "normalizedScope in governedWriteScopes" "$CREDENTIALS_TEMPLATE" "Accounts template groups governed-write scopes under governance"
expect_fixed "scope in ['incidents:read', 'syncstate:read', 'syncstate:write', 'webhooks:dlq:read', 'webhooks:dlq:replay']" "$CREDENTIALS_TEMPLATE" "Accounts template no longer force-adds draft-write scope when writes are disabled"
expect_fixed "filterUnavailableScopes" "$PLUGIN_ROOT/src/services/CredentialService.php" "Credential service filters unavailable scopes before persisting managed accounts"
expect_fixed "{% if notificationEnabled %}" "$DASHBOARD_TEMPLATE" "Dashboard readiness view only renders operator notifications when notifications are enabled"
expect_fixed "recipientLabel" "$PLUGIN_ROOT/src/services/NotificationService.php" "Notification service enriches recent delivery rows with recipient labels"
expect_fixed "recipientCpEditUrl" "$PLUGIN_ROOT/src/services/NotificationService.php" "Notification service enriches recent delivery rows with recipient CP edit URLs"
expect_fixed "agents-operator-notifications-recipient-channel" "$DASHBOARD_TEMPLATE" "Dashboard notifications table renders recipient channel labels next to recipient identities"
expect_fixed "Last captured:" "$DASHBOARD_TEMPLATE" "Dashboard readiness view surfaces webhook test sink capture status"
expect_fixed "Captures:" "$DASHBOARD_TEMPLATE" "Dashboard readiness view exposes webhook test sink captures section"
expect_fixed "actionInput('agents/dashboard/send-webhook-test-sink-delivery')" "$DASHBOARD_TEMPLATE" "Dashboard readiness view exposes webhook test sink send action"
expect_fixed "actionInput('agents/dashboard/clear-webhook-test-sink')" "$DASHBOARD_TEMPLATE" "Dashboard readiness view exposes webhook test sink clear action"
expect_fixed "actionInput('agents/dashboard/clear-status-verdicts')" "$DASHBOARD_TEMPLATE" "Dashboard readiness view exposes stale-status reset action"
expect_fixed "public function actionClearStatusVerdicts(): Response" "$DASHBOARD_CONTROLLER" "Dashboard controller exposes stale-status reset action"
expect_fixed "public function clearRuntimeCounters(): int" "$PLUGIN_ROOT/src/services/ObservabilityMetricsService.php" "Observability metrics service can clear cache-backed runtime counters"
expect_fixed "statusScreenPreview" "$DASHBOARD_TEMPLATE" "Dashboard readiness view supports lightweight status screen preview modes"
expect_fixed "data-agents-open-status-details=\"statusSystemDetails\"" "$DASHBOARD_TEMPLATE" "Dashboard readiness view exposes a system-details opener for preview screens"
expect_fixed "agents-status-screen-summary-grid" "$DASHBOARD_TEMPLATE" "Dashboard readiness view renders lightweight preview summary cards"
expect_fixed "Advanced tools" "$DASHBOARD_TEMPLATE" "Dashboard readiness view groups advanced tools separately in preview mode"
expect_fixed "Start with one account" "$DASHBOARD_TEMPLATE" "Dashboard readiness preview includes setup guidance copy"
expect_fixed "Everything looks healthy" "$DASHBOARD_TEMPLATE" "Dashboard readiness preview includes operational guidance copy"
expect_fixed "Fix the blocking issue first" "$DASHBOARD_TEMPLATE" "Dashboard readiness preview includes incident guidance copy"
expect_fixed "id=\"credentialsPolicyDetailDialog\"" "$DASHBOARD_TEMPLATE" "Dashboard readiness view exposes credentials/policy detail dialog"
expect_fixed "data-agents-detail-open=\"credentialsPolicyDetailDialog\"" "$DASHBOARD_TEMPLATE" "Dashboard readiness view exposes credentials/policy detail trigger"
expect_fixed "id=\"confidenceObservabilityDetailDialog\"" "$DASHBOARD_TEMPLATE" "Dashboard readiness view exposes confidence/observability detail dialog"
expect_fixed "data-agents-detail-open=\"confidenceObservabilityDetailDialog\"" "$DASHBOARD_TEMPLATE" "Dashboard readiness view exposes confidence/observability detail trigger"
expect_fixed "id=\"integrationCapacityDetailDialog\"" "$DASHBOARD_TEMPLATE" "Dashboard readiness view exposes integration/capacity detail dialog"
expect_fixed "data-agents-detail-open=\"integrationCapacityDetailDialog\"" "$DASHBOARD_TEMPLATE" "Dashboard readiness view exposes integration/capacity detail trigger"
expect_fixed "id=\"securityActionMappingSection\"" "$DASHBOARD_TEMPLATE" "Dashboard readiness view preserves security action mapping anchor compatibility"
expect_fixed "id=\"webhookDlqDetailSection\"" "$DASHBOARD_TEMPLATE" "Dashboard security view preserves webhook DLQ operational section"
expect_fixed "securityLatestDlqUpdatedAt" "$DASHBOARD_TEMPLATE" "Dashboard security view guards empty DLQ latest-update access"
expect_fixed "id=\"webhookSection\"" "$SETTINGS_TEMPLATE" "Settings template exposes webhook configuration section"
expect_fixed "settingsFocusRuntime" "$SETTINGS_TEMPLATE" "Settings template exposes runtime focus panel"
expect_fixed "settingsFocusDelivery" "$SETTINGS_TEMPLATE" "Settings template exposes delivery focus panel"
expect_fixed "settingsFocusMonitoring" "$SETTINGS_TEMPLATE" "Settings template exposes monitoring focus panel"
expect_fixed "id: 'webhookUrl'" "$SETTINGS_TEMPLATE" "Settings template exposes webhook URL env-aware field"
expect_fixed "suggestAliases: true" "$SETTINGS_TEMPLATE" "Settings template supports alias suggestions for webhook URL"
expect_fixed "This can begin with an environment variable or alias." "$SETTINGS_TEMPLATE" "Settings template preserves Craft-native webhook URL env tip"
expect_fixed "id: 'webhookSecret'" "$SETTINGS_TEMPLATE" "Settings template exposes webhook secret env-aware field"
expect_fixed "This can begin with an environment variable." "$SETTINGS_TEMPLATE" "Settings template preserves Craft-native webhook secret env tip"
expect_fixed "disabled: webhookUrlSettingLocked" "$SETTINGS_TEMPLATE" "Settings template disables webhook URL when config-locked"
expect_fixed "disabled: webhookSecretSettingLocked" "$SETTINGS_TEMPLATE" "Settings template disables webhook secret when config-locked"
expect_fixed "data-agents-settings-focus-tabs" "$SETTINGS_TAB_TEMPLATE" "Settings page template exposes focus-tab wrapper"
expect_fixed "{% set tabs = {} %}" "$SETTINGS_TAB_TEMPLATE" "Settings page template initializes native Craft tabs"
expect_fixed "label: tab.label" "$SETTINGS_TAB_TEMPLATE" "Settings page template maps focus sections into native Craft tabs"
expect_fixed "url: '#' ~ tab.panelId" "$SETTINGS_TAB_TEMPLATE" "Settings page template links native Craft tabs to focus panels"
expect_fixed "document.querySelectorAll('#tabs [data-id]')" "$SETTINGS_TAB_TEMPLATE" "Settings page template wires panel switching from native Craft tabs"
expect_fixed "public string \$webhookUrl = '\$PLUGIN_AGENTS_WEBHOOK_URL';" "$SETTINGS_MODEL" "Settings model defaults webhook URL to env reference"
expect_fixed "public string \$webhookSecret = '\$PLUGIN_AGENTS_WEBHOOK_SECRET';" "$SETTINGS_MODEL" "Settings model defaults webhook secret to env reference"
expect_fixed "resolveWebhookTransportSettings" "$SECURITY_POLICY_SERVICE" "Security policy resolves webhook transport from settings"
expect_fixed "'webhookUrl' => \$webhookUrl" "$SECURITY_POLICY_SERVICE" "Security policy runtime config exposes resolved webhook URL"
expect_fixed "'webhookSecret' => \$webhookSecret" "$SECURITY_POLICY_SERVICE" "Security policy runtime config exposes resolved webhook secret"
expect_fixed "<span>Approved</span>" "$CONTROL_TEMPLATE" "Control CP template exposes unified approved section"
expect_fixed "Applied / Completed" "$CONTROL_TEMPLATE" "Control CP template exposes applied/completed terminal section"
expect_fixed "agents-control-journey-divider__dot" "$CONTROL_TEMPLATE" "Control CP template renders centered divider dots between approval journey cards"
expect_fixed "agents-control-journey-break" "$CONTROL_TEMPLATE" "Control CP template renders edge-to-edge breaks before embedded rules cards"
expect_fixed "data-target=\"{{ pendingTablePanelId }}\"" "$CONTROL_TEMPLATE" "Control CP template allows Pending card to collapse from the title row"
expect_fixed "<span>Pending</span>" "$CONTROL_TEMPLATE" "Control CP template labels the first approvals stage as Pending"
expect_fixed "data-target=\"{{ approvedTablePanelId }}\"" "$CONTROL_TEMPLATE" "Control CP template allows Approved card to collapse from the title row"
expect_fixed "data-target=\"{{ rulesTablePanelId }}\"" "$CONTROL_TEMPLATE" "Control CP template exposes toggleable embedded rules table card on the Approvals page"
expect_fixed "data-target=\"{{ rulesFormPanelId }}\"" "$CONTROL_TEMPLATE" "Control CP template exposes toggleable embedded rule form card on the Approvals page"
expect_fixed "{% set title = \"Agents Approvals\" %}" "$CONTROL_TEMPLATE" "Control CP template exposes Approvals page title"
expect_fixed "approval.actionLabel" "$CONTROL_TEMPLATE" "Control CP template renders human-readable action labels"
expect_fixed "approval.decidedByLabel" "$CONTROL_TEMPLATE" "Control CP template shows human-readable approver labels"
expect_fixed "execute automatically once required approvals are complete" "$CONTROL_TEMPLATE" "Control CP template explains auto-execution on approval"
expect_fixed "'Approve ' ~ approvalButtonIndex" "$CONTROL_TEMPLATE" "Control CP template exposes numbered high-risk approval buttons"
expect_fixed "elements/apply-draft" "$CONTROL_TEMPLATE" "Control CP template exposes apply-draft action from approved rows"
expect_fixed "and approval.targetEntryDraftRecordId" "$CONTROL_TEMPLATE" "Control CP template gates Apply Draft on saved draft availability"
expect_fixed "Bound draft" "$CONTROL_TEMPLATE" "Control CP template surfaces exact bound draft identity on approved requests"
expect_fixed "js-control-view-diff" "$CONTROL_TEMPLATE" "Control CP template exposes dedicated Diff actions"
expect_fixed "agentsControlDiffModal" "$CONTROL_TEMPLATE" "Control CP template renders the approval diff modal shell"
expect_fixed "controlDiffUrl" "$CONTROL_TEMPLATE" "Control CP template passes the approval diff endpoint to the client"
expect_fixed "Approval diff #" "$CONTROL_TEMPLATE" "Control CP template labels the diff modal per approval"
expect_fixed "id: 'agentsControlDiffTabs'" "$CONTROL_TEMPLATE" "Control CP template renders the diff modal with Craft pane-tabs"
expect_fixed "label: 'Structured'," "$CONTROL_TEMPLATE" "Control CP template renders the Structured diff tab"
expect_fixed "label: 'Focus'," "$CONTROL_TEMPLATE" "Control CP template renders the Focus diff tab"
expect_absent "label: 'Redline'," "$CONTROL_TEMPLATE" "Control CP template no longer renders the Redline diff tab"
expect_fixed "id=\"agentsControlFocusToolbar\"" "$CONTROL_TEMPLATE" "Control CP template renders a Focus-local before/after toolbar"
expect_fixed "data-agents-focus-mode=\"after\"" "$CONTROL_TEMPLATE" "Control CP template exposes the Focus After view toggle"
expect_fixed "data-agents-focus-mode=\"before\"" "$CONTROL_TEMPLATE" "Control CP template exposes the Focus Before view toggle"
expect_fixed "(…)" "$CONTROL_TEMPLATE" "Control CP template uses an ellipsis marker in Focus truncation gaps"
expect_absent "(...)" "$CONTROL_TEMPLATE" "Control CP template no longer uses three-dot Focus truncation gaps"
expect_fixed "agentsControlRedlineRows" "$CONTROL_TEMPLATE" "Control CP template renders the redline diff panel"
expect_fixed "renderRedlineRows" "$CONTROL_TEMPLATE" "Control CP template renders inline redline rows from the diff payload"
expect_fixed "{% if change.label == 'Draft notes' %}" "$CONTROL_TEMPLATE" "Control CP template extracts draft notes from review summaries"
expect_fixed "<strong>Draft notes:</strong> {{ reviewDraftNotes }}" "$CONTROL_TEMPLATE" "Control CP template shows draft notes inline in pending approvals"
expect_fixed "<strong>Target set:</strong> {{ approval.targetSetSummary }}" "$CONTROL_TEMPLATE" "Control CP template shows target-set summary inline in pending approvals"
expect_absent "<span>Proposed changes</span>" "$CONTROL_TEMPLATE" "Control CP template no longer renders the Proposed changes toggle in pending approvals"
expect_absent "<div class=\"agents-control-pending-table__meta\">Ref: {{ approval.actionRef ?: 'n/a' }}</div>" "$CONTROL_TEMPLATE" "Control CP template no longer renders the pending approval action ref line"
expect_fixed "Existing draft" "$CONTROL_TEMPLATE" "Control CP template surfaces conflicting draft details in approval follow-up views"
expect_fixed "more conflicting drafts" "$CONTROL_TEMPLATE" "Control CP template summarizes additional conflicting drafts when present"
expect_fixed "getCpPosture()" "$ADOPTION_SERVICE" "Adoption metrics service uses existing security posture API"
expect_fixed "for (\$attempt = 0; \$attempt < 4; \$attempt++)" "$CONTROL_SERVICE" "Control approval decisions use optimistic concurrency retries"
expect_fixed "'secondaryDecisionBy' => null" "$CONTROL_SERVICE" "Control approval updates guard dual-approval second-decision races"
expect_fixed "entry.updatedraft" "$CONTROL_SERVICE" "Control execution service supports entry.updateDraft action"
expect_fixed "executeApprovedActionFromApprovalId" "$CONTROL_SERVICE" "Control execution service supports one-click execution from approved request"
expect_fixed "public function getApprovalById(int \$approvalId): ?array" "$CONTROL_SERVICE" "Control execution service exposes single approval lookup for CP diff review"
expect_fixed "public function getLatestExecutionForApproval(int \$approvalId): ?array" "$CONTROL_SERVICE" "Control execution service exposes latest execution lookup for CP diff review"
expect_fixed "findConflictingSavedDraftsForCanonical" "$CONTROL_SERVICE" "Control execution service checks for conflicting saved drafts before creating governed drafts"
expect_fixed "savedDraftsOnly()" "$CONTROL_SERVICE" "Control execution service limits governed draft conflict checks to saved drafts"
expect_fixed "'conflictType' => 'savedDraftExists'" "$CONTROL_SERVICE" "Control execution service reports saved-draft conflicts explicitly"
expect_fixed "Provide payload.draftId to target an exact saved draft." "$CONTROL_SERVICE" "Control execution service instructs callers to target an explicit draft when conflicts exist"
expect_fixed "APPROVAL_DRAFT_EXECUTION_METADATA_KEY" "$CONTROL_SERVICE" "Control execution service persists approval-bound draft execution metadata"
expect_fixed "APPROVAL_TARGET_SET_METADATA_KEY" "$CONTROL_SERVICE" "Control execution service persists target-set metadata on approvals"
expect_fixed "APPROVAL_REQUESTER_METADATA_KEY" "$CONTROL_SERVICE" "Control execution service persists requesting credential metadata on approvals"
expect_fixed "applyApprovalTargetSetConstraints" "$CONTROL_SERVICE" "Control execution service validates target-set bounds at approval request time"
expect_fixed "evaluateExecutionTargetSetConstraints" "$CONTROL_SERVICE" "Control execution service revalidates target-set bounds at execution time"
expect_fixed "Target set violation:" "$CONTROL_SERVICE" "Control execution service emits explicit target-set violation messages"
expect_fixed "syncApprovalDraftExecutionMetadata" "$CONTROL_SERVICE" "Control execution service syncs exact draft identity back onto approvals"
expect_fixed "'draftRecordId' => (int)(\$draft->draftId ?? 0)" "$CONTROL_SERVICE" "Control execution service records saved draft record ids in execution payloads"
expect_fixed "hasMultipleActiveCpUsers" "$CONTROL_SERVICE" "Control required-approvals logic degrades to single approval when only one active user exists"
expect_fixed "APPROVAL_ASSURANCE_DEGRADED" "$CONTROL_SERVICE" "Control plane persists explicit degraded approval assurance mode"
expect_fixed "Approval must be decided by a different actor than the requester." "$CONTROL_SERVICE" "Control plane enforces requester/approver separation outside degraded fallback"
expect_fixed "assuranceModeLabel" "$CONTROL_SERVICE" "Control plane hydrates assurance metadata for operator surfaces"
expect_fixed "Assurance:" "$CONTROL_TEMPLATE" "Control CP surfaces approval assurance details"

echo "Control/consumer regression checks completed."
