#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

fail() {
  echo "FAIL: $1"
  exit 1
}

pass() {
  echo "PASS: $1"
}

expect_fixed() {
  local needle="$1"
  local file="$2"
  local description="$3"
  if grep -Fq "$needle" "$file"; then
    pass "$description"
    return
  fi
  fail "$description (missing: $needle in $file)"
}

expect_pattern() {
  local pattern="$1"
  local file="$2"
  local description="$3"
  if grep -Eq "$pattern" "$file"; then
    pass "$description"
    return
  fi
  fail "$description (missing pattern: $pattern in $file)"
}

CREDENTIAL_SERVICE="$PLUGIN_ROOT/src/services/CredentialService.php"
SECURITY_SERVICE="$PLUGIN_ROOT/src/services/SecurityPolicyService.php"
API_CONTROLLER="$PLUGIN_ROOT/src/controllers/ApiController.php"
DASHBOARD_CONTROLLER="$PLUGIN_ROOT/src/controllers/DashboardController.php"
PLUGIN_FILE="$PLUGIN_ROOT/src/Plugin.php"
MIGRATION_FILE="$PLUGIN_ROOT/src/migrations/m260226_180000_add_agents_credentials_table.php"
PAUSE_MIGRATION_FILE="$PLUGIN_ROOT/src/migrations/m260305_110000_add_credential_pause_column.php"
OWNER_MIGRATION_FILE="$PLUGIN_ROOT/src/migrations/m260306_100000_add_credential_owner_column.php"
FORCE_APPROVAL_MIGRATION_FILE="$PLUGIN_ROOT/src/migrations/m260307_150000_add_credential_force_human_approval_column.php"
USER_RELATION_MIGRATION_FILE="$PLUGIN_ROOT/src/migrations/m260313_160000_add_credential_user_relation_columns.php"
DESCRIPTION_MIGRATION_FILE="$PLUGIN_ROOT/src/migrations/m260313_180000_add_credential_description_column.php"
CP_TEMPLATE="$PLUGIN_ROOT/src/templates/credentials.twig"

expect_fixed "agents_credentials" "$MIGRATION_FILE" "Managed credentials migration defines credentials table"
expect_fixed "'tokenHash'" "$MIGRATION_FILE" "Managed credentials migration includes token hash column"
expect_fixed "pausedAt" "$PAUSE_MIGRATION_FILE" "Managed credentials pause migration defines pausedAt column"
expect_fixed "owner" "$OWNER_MIGRATION_FILE" "Managed credentials owner migration defines owner column"
expect_fixed "forceHumanApproval" "$FORCE_APPROVAL_MIGRATION_FILE" "Managed credentials force-human-approval migration defines column"
expect_fixed "ownerUserId" "$USER_RELATION_MIGRATION_FILE" "Managed credentials user-relation migration defines owner user column"
expect_fixed "approvalRecipientUserIds" "$USER_RELATION_MIGRATION_FILE" "Managed credentials user-relation migration defines approval recipient column"
expect_fixed "description" "$DESCRIPTION_MIGRATION_FILE" "Managed credentials description migration defines description column"
expect_fixed "class CredentialService extends Component" "$CREDENTIAL_SERVICE" "CredentialService class exists"
expect_fixed "createManagedCredential" "$CREDENTIAL_SERVICE" "CredentialService supports credential creation"
expect_fixed "updateManagedCredential" "$CREDENTIAL_SERVICE" "CredentialService supports credential profile/scope updates"
expect_fixed "rotateManagedCredential" "$CREDENTIAL_SERVICE" "CredentialService supports credential rotation"
expect_fixed "revokeManagedCredential" "$CREDENTIAL_SERVICE" "CredentialService supports credential revocation"
expect_fixed "deleteManagedCredential" "$CREDENTIAL_SERVICE" "CredentialService supports credential deletion"
expect_fixed "recordCredentialUse" "$CREDENTIAL_SERVICE" "CredentialService tracks last-used metadata"
expect_fixed "pauseManagedCredential" "$CREDENTIAL_SERVICE" "CredentialService supports reversible pause"
expect_fixed "resumeManagedCredential" "$CREDENTIAL_SERVICE" "CredentialService supports reversible resume"
expect_fixed "getManagedCredentialByIdForCp" "$CREDENTIAL_SERVICE" "CredentialService exposes CP credential lookup by ID"
expect_fixed "supportsOwnerColumn" "$CREDENTIAL_SERVICE" "CredentialService supports owner column detection"
expect_fixed "supportsDescriptionColumn" "$CREDENTIAL_SERVICE" "CredentialService supports description column detection"
expect_fixed "supportsOwnerUserIdColumn" "$CREDENTIAL_SERVICE" "CredentialService supports owner user relation detection"
expect_fixed "supportsForceHumanApprovalColumn" "$CREDENTIAL_SERVICE" "CredentialService supports force-human-approval column detection"
expect_fixed "supportsApprovalRecipientUserIdsColumn" "$CREDENTIAL_SERVICE" "CredentialService supports approval-recipient relation detection"
expect_fixed "normalizeOwner" "$CREDENTIAL_SERVICE" "CredentialService normalizes owner values"
expect_fixed "getNotificationTargetsForHandle" "$CREDENTIAL_SERVICE" "CredentialService exposes account-specific notification target lookup"
expect_fixed "Unable to generate a secure API token because random_bytes() failed." "$CREDENTIAL_SERVICE" "CredentialService fails closed when secure token entropy is unavailable"

if grep -Fq "uniqid('', true) . microtime(true)" "$CREDENTIAL_SERVICE"; then
  fail "CredentialService must not fall back to uniqid/microtime token entropy"
fi
pass "CredentialService has no predictable token-entropy fallback"

expect_fixed "getManagedCredentialsForRuntime" "$SECURITY_SERVICE" "Security policy consumes managed credentials for runtime auth"
expect_fixed "managedCredentialCount" "$SECURITY_SERVICE" "Security posture exposes managed credential counts"
expect_fixed "recordCredentialUse" "$API_CONTROLLER" "API auth path records managed credential usage"

expect_fixed "actionCredentials" "$DASHBOARD_CONTROLLER" "Dashboard controller exposes credentials tab"
expect_fixed "actionCreateCredential" "$DASHBOARD_CONTROLLER" "Dashboard controller supports credential creation action"
expect_fixed "actionUpdateCredential" "$DASHBOARD_CONTROLLER" "Dashboard controller supports credential update action"
expect_fixed "actionRotateCredential" "$DASHBOARD_CONTROLLER" "Dashboard controller supports credential rotation action"
expect_fixed "actionRevokeCredential" "$DASHBOARD_CONTROLLER" "Dashboard controller supports credential revoke action"
expect_fixed "actionDeleteCredential" "$DASHBOARD_CONTROLLER" "Dashboard controller supports credential delete action"
expect_fixed "actionPauseCredential" "$DASHBOARD_CONTROLLER" "Dashboard controller supports agent pause action"
expect_fixed "actionResumeCredential" "$DASHBOARD_CONTROLLER" "Dashboard controller supports agent resume action"
expect_fixed "actionTestCredential" "$DASHBOARD_CONTROLLER" "Dashboard controller supports account validation action"
expect_fixed "buildCredentialTestResult" "$DASHBOARD_CONTROLLER" "Dashboard controller centralizes account validation results for sync and async use"
expect_fixed "getAcceptsJson()" "$DASHBOARD_CONTROLLER" "Dashboard controller supports async JSON account validation responses"
expect_fixed "buildWorkerEnvExport" "$DASHBOARD_CONTROLLER" "Dashboard controller can return worker env exports for async rotate responses"
expect_fixed "buildWorkerEnvFilename" "$DASHBOARD_CONTROLLER" "Dashboard controller can return worker env filenames for async rotate responses"
expect_fixed "credentialOwnerLegacyValue" "$DASHBOARD_CONTROLLER" "Dashboard controller parses legacy owner fallback input"
expect_fixed "credentialDescription" "$DASHBOARD_CONTROLLER" "Dashboard controller parses credential description input"
expect_fixed "credentialOwnerUserId" "$DASHBOARD_CONTROLLER" "Dashboard controller parses credential owner relation input"
expect_fixed "credentialApprovalRecipientUserIds" "$DASHBOARD_CONTROLLER" "Dashboard controller parses approval recipient relation input"
expect_fixed "credentialForceHumanApproval" "$DASHBOARD_CONTROLLER" "Dashboard controller parses force-human-approval input"
expect_fixed "parseBooleanBodyParam('credentialForceHumanApproval', false)" "$DASHBOARD_CONTROLLER" "Force-human-approval parser defaults unchecked lightswitch to false"
expect_fixed "resolveCurrentCpUserId" "$DASHBOARD_CONTROLLER" "Dashboard controller resolves current CP user ID for owner prefill"
expect_fixed "resolveCurrentCpUserEmail" "$DASHBOARD_CONTROLLER" "Dashboard controller resolves current CP user email for owner prefill"
expect_fixed "requireCredentialPermission" "$DASHBOARD_CONTROLLER" "Dashboard controller enforces credential permissions"
expect_fixed "canCredentialPermission" "$DASHBOARD_CONTROLLER" "Dashboard controller exposes credential permission checks"

expect_fixed "CredentialService::class" "$PLUGIN_FILE" "Plugin registers CredentialService component"
expect_fixed "'agents/accounts'" "$PLUGIN_FILE" "Plugin exposes CP credentials route/subnav"
expect_fixed "\$item['url'] = 'agents';" "$PLUGIN_FILE" "Plugin top-level nav keeps the Agents section active across subnav pages"
expect_fixed "'agents' => 'agents/dashboard/index'" "$PLUGIN_FILE" "Plugin root CP route uses a redirect entrypoint for Accounts"
expect_fixed "return \$this->redirect('agents/accounts');" "$DASHBOARD_CONTROLLER" "Dashboard controller redirects the plugin root to Accounts"
expect_fixed "redirect(UrlHelper::cpUrl('agents/settings'))" "$PLUGIN_FILE" "Plugin settings entrypoint lands on Settings"
expect_fixed "settings/plugins" "$PLUGIN_FILE" "Plugin can detect the Settings > Plugins index for link overrides"
expect_fixed "tr[data-handle=\"agents\"]" "$PLUGIN_FILE" "Plugin rewrites the Agents icon link on the Settings > Plugins index"
expect_fixed "UrlHelper::cpUrl('agents/settings')" "$PLUGIN_FILE" "Plugin points the Settings > Plugins icon to the Agents settings page"
expect_fixed "EVENT_REGISTER_PERMISSIONS" "$PLUGIN_FILE" "Plugin registers custom credential permissions"
expect_fixed "PERMISSION_CREDENTIALS_MANAGE" "$PLUGIN_FILE" "Plugin defines credential permission constants"
expect_fixed "<h1>Accounts</h1>" "$CP_TEMPLATE" "Accounts CP template is present"
expect_fixed "pause-credential" "$CP_TEMPLATE" "Accounts CP template supports pause action"
expect_fixed "resume-credential" "$CP_TEMPLATE" "Accounts CP template supports resume action"
expect_fixed "update-credential" "$CP_TEMPLATE" "Credentials CP template supports update action"
expect_fixed "delete-credential" "$CP_TEMPLATE" "Credentials CP template supports delete action"
expect_fixed "credentialDescription" "$CP_TEMPLATE" "Credentials CP template includes description input"
expect_fixed "credentialOwnerUserId" "$CP_TEMPLATE" "Credentials CP template includes owner relation input"
expect_fixed "credentialOwnerLegacyValue" "$CP_TEMPLATE" "Credentials CP template preserves legacy owner fallback"
expect_fixed "credentialApprovalRecipientUserIds" "$CP_TEMPLATE" "Credentials CP template includes approval recipient relation input"
expect_fixed "credentialForceHumanApproval" "$CP_TEMPLATE" "Credentials CP template includes force-human-approval controls"
expect_fixed "Account Templates" "$CP_TEMPLATE" "Credentials CP template exposes dedicated account templates section"
expect_fixed "agent-entry-translation-drafts" "$CP_TEMPLATE" "Credentials CP template exposes the translation-drafts account template"
expect_fixed "Entry Translation Drafts" "$CP_TEMPLATE" "Credentials CP template names the translation-drafts account template"
expect_fixed "agents-capability-group-title" "$CP_TEMPLATE" "Credentials CP template groups scopes by type"
expect_fixed "scope in ['incidents:read', 'syncstate:read', 'syncstate:write', 'webhooks:dlq:read', 'webhooks:dlq:replay']" "$CP_TEMPLATE" "Credentials CP template force-adds canonical sync-state and webhook DLQ scopes into the picker"
expect_fixed "id=\"agentsAccountsViewSwitch\"" "$CP_TEMPLATE" "Credentials CP template renders a Craft-style Accounts view switch"
expect_fixed "data-agent-view-mode=\"table\"" "$CP_TEMPLATE" "Credentials CP template exposes a table view toggle for Accounts"
expect_fixed "data-agent-view-mode=\"cards\"" "$CP_TEMPLATE" "Credentials CP template exposes a card view toggle for Accounts"
expect_pattern "<table class=\"data fullwidth( big)? agents-accounts-registry\"" "$CP_TEMPLATE" "Credentials CP template renders a table-style managed-account registry"
expect_pattern "<th scope=\"col\"[^>]*>Account</th>" "$CP_TEMPLATE" "Credentials CP template renders the Account registry column"
expect_pattern "<th scope=\"col\"[^>]*>State</th>" "$CP_TEMPLATE" "Credentials CP template renders the State registry column"
expect_pattern "<th scope=\"col\"[^>]*>Purpose</th>" "$CP_TEMPLATE" "Credentials CP template renders the Purpose registry column"
expect_pattern "<th scope=\"col\"[^>]*>Owner</th>" "$CP_TEMPLATE" "Credentials CP template renders the Owner registry column"
expect_pattern "<th scope=\"col\"[^>]*>Access</th>" "$CP_TEMPLATE" "Credentials CP template renders the Access registry column"
expect_pattern "<th scope=\"col\"[^>]*>Last used</th>" "$CP_TEMPLATE" "Credentials CP template renders the Last used registry column"
expect_pattern "<th scope=\"col\"[^>]*>Risk</th>" "$CP_TEMPLATE" "Credentials CP template renders the Risk registry column"
expect_pattern "<th scope=\"col\"[^>]*>Actions</th>" "$CP_TEMPLATE" "Credentials CP template renders the Actions registry column"
expect_fixed "simulatePulseMode" "$CP_TEMPLATE" "Credentials CP template supports pulse simulation mode query parameter"
expect_fixed "simulationEnabledIsCount" "$CP_TEMPLATE" "Credentials CP template supports numeric simulatePulse shorthand"
expect_fixed "simulatePulseAccounts" "$CP_TEMPLATE" "Credentials CP template supports targeted pulse simulation accounts"
expect_fixed "simulatePulseIntervalMs" "$CP_TEMPLATE" "Credentials CP template supports pulse simulation interval override"
expect_fixed "normalizeSimulationStartOptions" "$CP_TEMPLATE" "Credentials CP template normalizes pulse simulation options"
expect_fixed "credentialIdsByHandle" "$CP_TEMPLATE" "Credentials CP template can target pulse simulation by account handle"
expect_fixed "agents-agent-token-overlay" "$CP_TEMPLATE" "Credentials CP template renders the account-scoped token overlay"
expect_fixed "revealedCredentialOverlayClose" "$CP_TEMPLATE" "Credentials CP template includes a close control for the token overlay"
expect_fixed "agentsAccountsTableView" "$CP_TEMPLATE" "Credentials CP template renders the Accounts table view container"
expect_fixed "agentsAccountsCardsView" "$CP_TEMPLATE" "Credentials CP template preserves the Accounts card view container"
expect_fixed "data-agent-details-panel" "$CP_TEMPLATE" "Credentials CP template marks details panels for shared table/card behavior"
expect_fixed "data-agent-details-template" "$CP_TEMPLATE" "Credentials CP template stores shared account detail content in hidden templates"
expect_fixed "agents-account-details-modal-backdrop" "$CP_TEMPLATE" "Credentials CP template renders modal styling hooks for account details"
expect_fixed "agents-account-details-modal__token-overlay" "$CP_TEMPLATE" "Credentials CP template can render the rotate token overlay inside the details modal"
expect_fixed "agents-accounts-registry-wrap.is-editing-active tr[data-agent-detail-item][data-agent-view-mode=\"table\"]:not(.is-editing-target)" "$CP_TEMPLATE" "Credentials CP template dims unaffected table rows during inline edit"
expect_fixed "closeDetailModal({ restoreFocus: false });" "$CP_TEMPLATE" "Credentials CP template closes any open details modal before dispatching shared edit events"
expect_fixed "Form is shown below." "$CP_TEMPLATE" "Credentials CP template distinguishes table edit mode messaging from inline card edit mode"
expect_fixed "data-agent-status-dot" "$CP_TEMPLATE" "Credentials CP template exposes shared status indicators for table and cards"
expect_fixed "agents-agent-card-edit-trigger" "$CP_TEMPLATE" "Credentials CP template renders a cog-style direct edit trigger"
expect_fixed "test-credential" "$CP_TEMPLATE" "Credentials CP template exposes account validation posting points"
expect_fixed "Connect Worker" "$CP_TEMPLATE" "Credentials CP template groups bootstrap guidance inside the details pane"
expect_fixed "Download .env" "$CP_TEMPLATE" "Credentials CP template exposes worker env export during token reveal"
expect_fixed "revealedCredentialWorkerEnv" "$CP_TEMPLATE" "Credentials CP template renders one-time worker env export content"
expect_fixed "https://marcusscheller.com/docs/agents/api/scope-guide" "$CP_TEMPLATE" "Credentials CP template links to the public scope guide"
expect_fixed "Test Account" "$CP_TEMPLATE" "Credentials CP template includes a details-pane test action"
expect_fixed "data-agent-test-form" "$CP_TEMPLATE" "Credentials CP template marks account validation forms for async handling"
expect_fixed "agents-agent-card-detail-feedback" "$CP_TEMPLATE" "Credentials CP template renders inline async account-validation feedback"
expect_fixed "data-agent-rotate-form" "$CP_TEMPLATE" "Credentials CP template marks rotate forms for async handling"
expect_fixed "data-agent-revoke-form" "$CP_TEMPLATE" "Credentials CP template marks revoke forms for async handling"
expect_fixed "const normalizedWorkerEnv = workerEnv.endsWith(" "$CP_TEMPLATE" "Credentials CP template keeps worker env download JS syntactically intact"
expect_fixed "const showCpMessage = (message, tone = 'notice') => {" "$CP_TEMPLATE" "Credentials CP template routes lifecycle async feedback through CP notices"

echo "Credential lifecycle regression checks completed."
