#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

fail() {
  echo "FAIL: $1"
  exit 1
}

pass() {
  echo "PASS: $1"
}

expect_fixed() {
  local needle="$1"
  local file="$2"
  local description="$3"
  if grep -Fq -- "$needle" "$file"; then
    pass "$description"
    return
  fi
  fail "$description (missing: $needle in $file)"
}

expect_pattern() {
  local pattern="$1"
  local file="$2"
  local description="$3"
  if grep -Eq "$pattern" "$file"; then
    pass "$description"
    return
  fi
  fail "$description (missing pattern: $pattern in $file)"
}

expect_absent() {
  local needle="$1"
  local file="$2"
  local description="$3"
  if grep -Fq -- "$needle" "$file"; then
    fail "$description (unexpected: $needle in $file)"
  fi
  pass "$description"
}

CREDENTIAL_SERVICE="$PLUGIN_ROOT/src/services/CredentialService.php"
TARGET_SET_SERVICE="$PLUGIN_ROOT/src/services/TargetSetService.php"
SECURITY_SERVICE="$PLUGIN_ROOT/src/services/SecurityPolicyService.php"
API_CONTROLLER="$PLUGIN_ROOT/src/controllers/ApiController.php"
DASHBOARD_CONTROLLER="$PLUGIN_ROOT/src/controllers/DashboardController.php"
PLUGIN_FILE="$PLUGIN_ROOT/src/Plugin.php"
MIGRATION_FILE="$PLUGIN_ROOT/src/migrations/m260226_180000_add_agents_credentials_table.php"
PAUSE_MIGRATION_FILE="$PLUGIN_ROOT/src/migrations/m260305_110000_add_credential_pause_column.php"
OWNER_MIGRATION_FILE="$PLUGIN_ROOT/src/migrations/m260306_100000_add_credential_owner_column.php"
FORCE_APPROVAL_MIGRATION_FILE="$PLUGIN_ROOT/src/migrations/m260307_150000_add_credential_force_human_approval_column.php"
USER_RELATION_MIGRATION_FILE="$PLUGIN_ROOT/src/migrations/m260313_160000_add_credential_user_relation_columns.php"
DESCRIPTION_MIGRATION_FILE="$PLUGIN_ROOT/src/migrations/m260313_180000_add_credential_description_column.php"
TARGET_SET_MIGRATION_FILE="$PLUGIN_ROOT/src/migrations/m260317_160000_add_target_sets_tables.php"
CP_TEMPLATE="$PLUGIN_ROOT/src/templates/credentials.twig"
TARGET_SETS_TEMPLATE="$PLUGIN_ROOT/src/templates/target-sets.twig"

expect_fixed "agents_credentials" "$MIGRATION_FILE" "Managed credentials migration defines credentials table"
expect_fixed "'tokenHash'" "$MIGRATION_FILE" "Managed credentials migration includes token hash column"
expect_fixed "pausedAt" "$PAUSE_MIGRATION_FILE" "Managed credentials pause migration defines pausedAt column"
expect_fixed "owner" "$OWNER_MIGRATION_FILE" "Managed credentials owner migration defines owner column"
expect_fixed "forceHumanApproval" "$FORCE_APPROVAL_MIGRATION_FILE" "Managed credentials force-human-approval migration defines column"
expect_fixed "ownerUserId" "$USER_RELATION_MIGRATION_FILE" "Managed credentials user-relation migration defines owner user column"
expect_fixed "approvalRecipientUserIds" "$USER_RELATION_MIGRATION_FILE" "Managed credentials user-relation migration defines approval recipient column"
expect_fixed "description" "$DESCRIPTION_MIGRATION_FILE" "Managed credentials description migration defines description column"
expect_fixed "agents_target_sets" "$TARGET_SET_MIGRATION_FILE" "Target-set migration defines target sets table"
expect_fixed "agents_credential_target_sets" "$TARGET_SET_MIGRATION_FILE" "Target-set migration defines credential relation table"
expect_fixed "class CredentialService extends Component" "$CREDENTIAL_SERVICE" "CredentialService class exists"
expect_fixed "class TargetSetService extends Component" "$TARGET_SET_SERVICE" "TargetSetService class exists"
expect_fixed "saveCredentialTargetSetAssignments" "$TARGET_SET_SERVICE" "TargetSetService supports credential assignment persistence"
expect_fixed "resolveCredentialActionBounds" "$TARGET_SET_SERVICE" "TargetSetService exposes credential/action target bounds"
expect_fixed "createManagedCredential" "$CREDENTIAL_SERVICE" "CredentialService supports credential creation"
expect_fixed "updateManagedCredential" "$CREDENTIAL_SERVICE" "CredentialService supports credential profile/scope updates"
expect_fixed "rotateManagedCredential" "$CREDENTIAL_SERVICE" "CredentialService supports credential rotation"
expect_fixed "revokeManagedCredential" "$CREDENTIAL_SERVICE" "CredentialService supports credential revocation"
expect_fixed "deleteManagedCredential" "$CREDENTIAL_SERVICE" "CredentialService supports credential deletion"
expect_fixed "buildHandoffBundleFiles" "$CREDENTIAL_SERVICE" "CredentialService can build account handoff bundles"
expect_fixed "recordCredentialUse" "$CREDENTIAL_SERVICE" "CredentialService tracks last-used metadata"
expect_fixed "pauseManagedCredential" "$CREDENTIAL_SERVICE" "CredentialService supports reversible pause"
expect_fixed "resumeManagedCredential" "$CREDENTIAL_SERVICE" "CredentialService supports reversible resume"
expect_fixed "getManagedCredentialByIdForCp" "$CREDENTIAL_SERVICE" "CredentialService exposes CP credential lookup by ID"
expect_fixed "supportsOwnerColumn" "$CREDENTIAL_SERVICE" "CredentialService supports owner column detection"
expect_fixed "supportsDescriptionColumn" "$CREDENTIAL_SERVICE" "CredentialService supports description column detection"
expect_fixed "supportsOwnerUserIdColumn" "$CREDENTIAL_SERVICE" "CredentialService supports owner user relation detection"
expect_fixed "supportsForceHumanApprovalColumn" "$CREDENTIAL_SERVICE" "CredentialService supports force-human-approval column detection"
expect_fixed "supportsApprovalRecipientUserIdsColumn" "$CREDENTIAL_SERVICE" "CredentialService supports approval-recipient relation detection"
expect_fixed "normalizeOwner" "$CREDENTIAL_SERVICE" "CredentialService normalizes owner values"
expect_fixed "getNotificationTargetsForHandle" "$CREDENTIAL_SERVICE" "CredentialService exposes account-specific notification target lookup"
expect_fixed "Unable to generate a secure API token because random_bytes() failed." "$CREDENTIAL_SERVICE" "CredentialService fails closed when secure token entropy is unavailable"

if grep -Fq "uniqid('', true) . microtime(true)" "$CREDENTIAL_SERVICE"; then
  fail "CredentialService must not fall back to uniqid/microtime token entropy"
fi
pass "CredentialService has no predictable token-entropy fallback"

expect_fixed "getManagedCredentialsForRuntime" "$SECURITY_SERVICE" "Security policy consumes managed credentials for runtime auth"
expect_fixed "managedCredentialCount" "$SECURITY_SERVICE" "Security posture exposes managed credential counts"
expect_fixed "recordCredentialUse" "$API_CONTROLLER" "API auth path records managed credential usage"

expect_fixed "actionCredentials" "$DASHBOARD_CONTROLLER" "Dashboard controller exposes credentials tab"
expect_fixed "actionCreateCredential" "$DASHBOARD_CONTROLLER" "Dashboard controller supports credential creation action"
expect_fixed "actionUpdateCredential" "$DASHBOARD_CONTROLLER" "Dashboard controller supports credential update action"
expect_fixed "actionRotateCredential" "$DASHBOARD_CONTROLLER" "Dashboard controller supports credential rotation action"
expect_fixed "actionRevokeCredential" "$DASHBOARD_CONTROLLER" "Dashboard controller supports credential revoke action"
expect_fixed "actionDeleteCredential" "$DASHBOARD_CONTROLLER" "Dashboard controller supports credential delete action"
expect_fixed "actionDownloadCredentialHandoff" "$DASHBOARD_CONTROLLER" "Dashboard controller supports account handoff downloads"
expect_fixed "actionPauseCredential" "$DASHBOARD_CONTROLLER" "Dashboard controller supports agent pause action"
expect_fixed "actionResumeCredential" "$DASHBOARD_CONTROLLER" "Dashboard controller supports agent resume action"
expect_fixed "actionTestCredential" "$DASHBOARD_CONTROLLER" "Dashboard controller supports account validation action"
expect_fixed "actionCreateTargetSet" "$DASHBOARD_CONTROLLER" "Dashboard controller supports target-set creation"
expect_fixed "actionUpdateTargetSet" "$DASHBOARD_CONTROLLER" "Dashboard controller supports target-set updates"
expect_fixed "actionDeleteTargetSet" "$DASHBOARD_CONTROLLER" "Dashboard controller supports target-set deletion"
expect_fixed "actionTargetSets" "$DASHBOARD_CONTROLLER" "Dashboard controller exposes dedicated Target Sets page"
expect_fixed "buildCredentialTestResult" "$DASHBOARD_CONTROLLER" "Dashboard controller centralizes account validation results for sync and async use"
expect_fixed "getAcceptsJson()" "$DASHBOARD_CONTROLLER" "Dashboard controller supports async JSON account validation responses"
expect_fixed "buildWorkerEnvExport" "$DASHBOARD_CONTROLLER" "Dashboard controller can return worker env exports for async rotate responses"
expect_fixed "buildWorkerEnvFilename" "$DASHBOARD_CONTROLLER" "Dashboard controller can return worker env filenames for async rotate responses"
expect_fixed "sendBundleArchive" "$DASHBOARD_CONTROLLER" "Dashboard controller centralizes handoff archive delivery"
expect_fixed "credentialOwnerLegacyValue" "$DASHBOARD_CONTROLLER" "Dashboard controller parses legacy owner fallback input"
expect_fixed "credentialDescription" "$DASHBOARD_CONTROLLER" "Dashboard controller parses credential description input"
expect_fixed "credentialOwnerUserId" "$DASHBOARD_CONTROLLER" "Dashboard controller parses credential owner relation input"
expect_fixed "credentialApprovalRecipientUserIds" "$DASHBOARD_CONTROLLER" "Dashboard controller parses approval recipient relation input"
expect_fixed "credentialForceHumanApproval" "$DASHBOARD_CONTROLLER" "Dashboard controller parses force-human-approval input"
expect_fixed "parseBooleanBodyParam('credentialForceHumanApproval', false)" "$DASHBOARD_CONTROLLER" "Force-human-approval parser defaults unchecked lightswitch to false"
expect_fixed "resolveCurrentCpUserId" "$DASHBOARD_CONTROLLER" "Dashboard controller resolves current CP user ID for owner prefill"
expect_fixed "resolveCurrentCpUserEmail" "$DASHBOARD_CONTROLLER" "Dashboard controller resolves current CP user email for owner prefill"
expect_fixed "requireCredentialPermission" "$DASHBOARD_CONTROLLER" "Dashboard controller enforces credential permissions"
expect_fixed "canCredentialPermission" "$DASHBOARD_CONTROLLER" "Dashboard controller exposes credential permission checks"

expect_fixed "CredentialService::class" "$PLUGIN_FILE" "Plugin registers CredentialService component"
expect_fixed "TargetSetService::class" "$PLUGIN_FILE" "Plugin registers TargetSetService component"
expect_fixed "getTargetSetService" "$PLUGIN_FILE" "Plugin exposes TargetSetService getter"
expect_fixed "'agents/accounts'" "$PLUGIN_FILE" "Plugin exposes CP credentials route/subnav"
expect_fixed "'agents/target-sets'" "$PLUGIN_FILE" "Plugin exposes CP Target Sets route/subnav"
expect_fixed "\$item['url'] = 'agents';" "$PLUGIN_FILE" "Plugin top-level nav keeps the Agents section active across subnav pages"
expect_fixed "'agents' => 'agents/dashboard/index'" "$PLUGIN_FILE" "Plugin root CP route uses a redirect entrypoint for Accounts"
expect_fixed "return \$this->redirect('agents/accounts');" "$DASHBOARD_CONTROLLER" "Dashboard controller redirects the plugin root to Accounts"
expect_fixed "redirect(UrlHelper::cpUrl('agents/settings'))" "$PLUGIN_FILE" "Plugin settings entrypoint lands on Settings"
expect_fixed "settings/plugins" "$PLUGIN_FILE" "Plugin can detect the Settings > Plugins index for link overrides"
expect_fixed "tr[data-handle=\"agents\"]" "$PLUGIN_FILE" "Plugin rewrites the Agents icon link on the Settings > Plugins index"
expect_fixed "UrlHelper::cpUrl('agents/settings')" "$PLUGIN_FILE" "Plugin points the Settings > Plugins icon to the Agents settings page"
expect_fixed "EVENT_REGISTER_PERMISSIONS" "$PLUGIN_FILE" "Plugin registers custom credential permissions"
expect_fixed "PERMISSION_CREDENTIALS_MANAGE" "$PLUGIN_FILE" "Plugin defines credential permission constants"
expect_fixed "<h1>Accounts</h1>" "$CP_TEMPLATE" "Accounts CP template is present"
expect_fixed "pause-credential" "$CP_TEMPLATE" "Accounts CP template supports pause action"
expect_fixed "resume-credential" "$CP_TEMPLATE" "Accounts CP template supports resume action"
expect_fixed "update-credential" "$CP_TEMPLATE" "Credentials CP template supports update action"
expect_fixed "delete-credential" "$CP_TEMPLATE" "Credentials CP template supports delete action"
expect_fixed "credentialDescription" "$CP_TEMPLATE" "Credentials CP template includes description input"
expect_fixed "credentialOwnerUserId" "$CP_TEMPLATE" "Credentials CP template includes owner relation input"
expect_fixed "credentialOwnerLegacyValue" "$CP_TEMPLATE" "Credentials CP template preserves legacy owner fallback"
expect_fixed "credentialApprovalRecipientUserIds" "$CP_TEMPLATE" "Credentials CP template includes approval recipient relation input"
expect_fixed "credentialForceHumanApproval" "$CP_TEMPLATE" "Credentials CP template includes force-human-approval controls"
expect_fixed "credentialTargetSetIds" "$CP_TEMPLATE" "Credentials CP template includes target-set assignment controls"
expect_fixed "Manage target sets" "$CP_TEMPLATE" "Credentials CP template links to the dedicated Target Sets page"
expect_absent "id=\"targetSetsSection\"" "$CP_TEMPLATE" "Credentials CP template no longer renders the inline Target Sets manager section"
expect_absent "id=\"addAgentSection\"" "$CP_TEMPLATE" "Credentials CP template no longer renders the old Add Account section shell"
expect_absent "targetSetAllowedEntryIds" "$CP_TEMPLATE" "Credentials CP template no longer embeds allowed-entry target-set controls"
expect_absent "targetSetAllowedSiteIds" "$CP_TEMPLATE" "Credentials CP template no longer embeds allowed-site target-set controls"
expect_fixed "Governed write helpers" "$CP_TEMPLATE" "Credentials CP template exposes governed write helper snippets in account details"
expect_fixed "Governed content refresh" "$CP_TEMPLATE" "Credentials CP template exposes the governed content refresh helper for eligible accounts"
expect_fixed "governedContentRefreshWorkflowUrl" "$CP_TEMPLATE" "Credentials CP template links the governed content refresh workflow"
expect_fixed "Open manual request test" "$CP_TEMPLATE" "Credentials CP template can hand operators off to the manual request test tool"
expect_fixed "data-agent-download-worker-env" "$CP_TEMPLATE" "Credentials CP template exposes account-level worker env downloads in detail views"
expect_fixed "data-agent-copy-worker-env" "$CP_TEMPLATE" "Credentials CP template exposes account-level worker env copy actions in detail views"
expect_fixed "agents-worker-env-preview" "$CP_TEMPLATE" "Credentials CP template renders visible worker env previews in detail views"
expect_fixed "download-credential-handoff" "$CP_TEMPLATE" "Credentials CP template posts to the account handoff download action"
expect_fixed "Worker / Agent Handoff" "$CP_TEMPLATE" "Credentials CP template labels the account handoff surface clearly"
expect_fixed "Download handoff" "$CP_TEMPLATE" "Credentials CP template exposes account handoff download controls"
expect_absent "TARGET_SET_HANDLE=" "$CP_TEMPLATE" "Credentials CP template no longer renders target-set-specific worker env snippets"
expect_fixed "Account Templates" "$CP_TEMPLATE" "Credentials CP template exposes dedicated account templates section"
expect_fixed "agents-account-templates-panel" "$CP_TEMPLATE" "Credentials CP template wraps account templates in a collapsible panel"
expect_fixed "agent-entry-translation-drafts" "$CP_TEMPLATE" "Credentials CP template exposes the translation-drafts account template"
expect_fixed "Translation Drafts" "$CP_TEMPLATE" "Credentials CP template names the translation-drafts account template"
expect_fixed "agents-capability-group-title" "$CP_TEMPLATE" "Credentials CP template groups scopes by type"
expect_fixed "scope in ['incidents:read', 'syncstate:read', 'syncstate:write', 'webhooks:dlq:read', 'webhooks:dlq:replay', 'workflows:read', 'workflows:report']" "$CP_TEMPLATE" "Credentials CP template force-adds canonical sync-state, workflow, and webhook DLQ scopes into the picker"
expect_fixed "data-agent-view-mode=\"table\"" "$CP_TEMPLATE" "Credentials CP template marks table-row account items consistently"
expect_absent "id=\"agentsAccountsViewSwitch\"" "$CP_TEMPLATE" "Credentials CP template no longer renders the Accounts view switch"
expect_absent "data-agent-view-mode=\"cards\"" "$CP_TEMPLATE" "Credentials CP template no longer renders card-view account items"
expect_absent "agents-lifecycle-panel" "$CP_TEMPLATE" "Credentials CP template no longer renders the legacy lifecycle panel"
expect_pattern "<table class=\"data fullwidth( big)? agents-accounts-registry\"" "$CP_TEMPLATE" "Credentials CP template renders a table-style managed-account registry"
expect_fixed "agents-accounts-registry__col--icon" "$CP_TEMPLATE" "Credentials CP template renders the leading account icon column"
expect_fixed "agents-accounts-registry-account-icon" "$CP_TEMPLATE" "Credentials CP template renders the leading robot icon in account rows"
expect_pattern "<th scope=\"col\"[^>]*>Account</th>" "$CP_TEMPLATE" "Credentials CP template renders the Account registry column"
expect_pattern "<th scope=\"col\"[^>]*>State</th>" "$CP_TEMPLATE" "Credentials CP template renders the State registry column"
expect_pattern "<th scope=\"col\"[^>]*>Purpose</th>" "$CP_TEMPLATE" "Credentials CP template renders the Purpose registry column"
expect_pattern "<th scope=\"col\"[^>]*>Owner</th>" "$CP_TEMPLATE" "Credentials CP template renders the Owner registry column"
expect_pattern "<th scope=\"col\"[^>]*>Access</th>" "$CP_TEMPLATE" "Credentials CP template renders the Access registry column"
expect_pattern "<th scope=\"col\"[^>]*>Last used</th>" "$CP_TEMPLATE" "Credentials CP template renders the Last used registry column"
expect_fixed "{% set showRiskColumn = listFilter == 'attention' %}" "$CP_TEMPLATE" "Credentials CP template gates the Risk registry column behind the attention filter"
expect_fixed "{% if showRiskColumn %}" "$CP_TEMPLATE" "Credentials CP template conditionally renders attention-only table columns"
expect_pattern "<th scope=\"col\"[^>]*>Actions</th>" "$CP_TEMPLATE" "Credentials CP template renders the Actions registry column"
expect_fixed "simulatePulseMode" "$CP_TEMPLATE" "Credentials CP template supports pulse simulation mode query parameter"
expect_fixed "simulationEnabledIsCount" "$CP_TEMPLATE" "Credentials CP template supports numeric simulatePulse shorthand"
expect_fixed "simulatePulseAccounts" "$CP_TEMPLATE" "Credentials CP template supports targeted pulse simulation accounts"
expect_fixed "simulatePulseIntervalMs" "$CP_TEMPLATE" "Credentials CP template supports pulse simulation interval override"
expect_fixed "normalizeSimulationStartOptions" "$CP_TEMPLATE" "Credentials CP template normalizes pulse simulation options"
expect_fixed "credentialIdsByHandle" "$CP_TEMPLATE" "Credentials CP template can target pulse simulation by account handle"
expect_fixed "agents-agent-token-overlay" "$CP_TEMPLATE" "Credentials CP template renders the account-scoped token overlay"
expect_fixed "revealedCredentialOverlayClose" "$CP_TEMPLATE" "Credentials CP template includes a close control for the token overlay"
expect_fixed "agentsAccountsTableView" "$CP_TEMPLATE" "Credentials CP template renders the Accounts table view container"
expect_absent "agentsAccountsCardsView" "$CP_TEMPLATE" "Credentials CP template no longer renders the Accounts card view container"
expect_fixed "data-agent-details-panel" "$CP_TEMPLATE" "Credentials CP template marks details panels for shared table/card behavior"
expect_fixed "data-agent-details-template" "$CP_TEMPLATE" "Credentials CP template stores shared account detail content in hidden templates"
expect_fixed "agents-account-details-modal-backdrop" "$CP_TEMPLATE" "Credentials CP template renders modal styling hooks for account details"
expect_fixed "agents-account-details-modal__token-overlay" "$CP_TEMPLATE" "Credentials CP template can render the rotate token overlay inside the details modal"
expect_fixed "agents-accounts-registry-wrap.is-editing-active tr[data-agent-detail-item][data-agent-view-mode=\"table\"]:not(.is-editing-target)" "$CP_TEMPLATE" "Credentials CP template dims unaffected table rows during inline edit"
expect_fixed "closeDetailModal({ restoreFocus: false });" "$CP_TEMPLATE" "Credentials CP template closes any open details modal before dispatching shared edit events"
expect_fixed "Form is shown below." "$CP_TEMPLATE" "Credentials CP template distinguishes table edit mode messaging from inline card edit mode"
expect_fixed "data-agent-status-dot" "$CP_TEMPLATE" "Credentials CP template exposes shared status indicators for table and cards"
expect_fixed "agents-agent-card-edit-trigger" "$CP_TEMPLATE" "Credentials CP template renders a cog-style direct edit trigger"
expect_fixed "test-credential" "$CP_TEMPLATE" "Credentials CP template exposes account validation posting points"
expect_fixed "Connect Agent" "$CP_TEMPLATE" "Credentials CP template groups bootstrap guidance inside the details pane"
expect_fixed "You set the boundary. External runtimes work inside it." "$CP_TEMPLATE" "Credentials CP template frames managed accounts as governed runtime boundaries"
expect_fixed "Broader than workflows" "$CP_TEMPLATE" "Credentials CP template flags accounts that are broader than attached workflows"
expect_fixed "workflow fit:" "$CP_TEMPLATE" "Credentials CP template exposes workflow fit details in account details"
expect_fixed "Download .env" "$CP_TEMPLATE" "Credentials CP template exposes worker env export during token reveal"
expect_fixed "revealedCredentialWorkerEnv" "$CP_TEMPLATE" "Credentials CP template renders one-time worker env export content"
expect_fixed "https://marcusscheller.com/docs/agents/api/scope-guide" "$CP_TEMPLATE" "Credentials CP template links to the public scope guide"
expect_fixed "Start from a reusable account profile built for common agency workflows." "$CP_TEMPLATE" "Credentials CP template frames default templates as reusable agency workflows"
expect_fixed "storage-layout.example.md" "$CREDENTIAL_SERVICE" "Account handoff bundles include storage layout guidance"
expect_fixed "OUTPUT_ROOT=" "$CREDENTIAL_SERVICE" "Account handoff env exports include an output root"
expect_fixed "smoke-test.sh" "$CREDENTIAL_SERVICE" "Account handoff bundles include a smoke test script"
expect_fixed "Content QA" "$CP_TEMPLATE" "Credentials CP template includes the Content QA template"
expect_fixed "Governed Content Drafts" "$CP_TEMPLATE" "Credentials CP template includes the governed drafts template"
expect_fixed "SEO & Metadata Auditor" "$CP_TEMPLATE" "Credentials CP template includes the SEO template"
expect_fixed "Commerce Catalog QA" "$CP_TEMPLATE" "Credentials CP template includes the commerce QA template"
expect_fixed "More templates" "$CP_TEMPLATE" "Credentials CP template includes the secondary template section"
expect_fixed "Accessibility Review" "$CP_TEMPLATE" "Credentials CP template includes the accessibility review template"
expect_fixed "Change Monitor" "$CP_TEMPLATE" "Credentials CP template includes the change monitor template"
expect_fixed "Launch QA" "$CP_TEMPLATE" "Credentials CP template includes the launch QA template"
expect_fixed "Use this template" "$CP_TEMPLATE" "Credentials CP template uses the template CTA label"
expect_absent "Site Structure Review Account" "$CP_TEMPLATE" "Credentials CP template no longer exposes the site structure review template in the shelf"
expect_fixed "Test Account" "$CP_TEMPLATE" "Credentials CP template includes a details-pane test action"
expect_fixed "data-agent-test-form" "$CP_TEMPLATE" "Credentials CP template marks account validation forms for async handling"
expect_fixed "agents-agent-card-detail-feedback" "$CP_TEMPLATE" "Credentials CP template renders inline async account-validation feedback"
expect_fixed "data-agent-rotate-form" "$CP_TEMPLATE" "Credentials CP template marks rotate forms for async handling"
expect_fixed "data-agent-revoke-form" "$CP_TEMPLATE" "Credentials CP template marks revoke forms for async handling"
expect_fixed "const normalizedWorkerEnv = workerEnv.endsWith(" "$CP_TEMPLATE" "Credentials CP template keeps worker env download JS syntactically intact"
expect_fixed "const showCpMessage = (message, tone = 'notice') => {" "$CP_TEMPLATE" "Credentials CP template routes lifecycle async feedback through CP notices"

expect_fixed "<h1>Target Sets</h1>" "$TARGET_SETS_TEMPLATE" "Target Sets CP template is present"
expect_fixed "selectedSubnavItem = \"targetSets\"" "$TARGET_SETS_TEMPLATE" "Target Sets CP template selects the Target Sets subnav item"
expect_fixed "Reusable write boundaries" "$TARGET_SETS_TEMPLATE" "Target Sets CP template explains the bounded write purpose"
expect_fixed "targetSetAllowedEntryIds" "$TARGET_SETS_TEMPLATE" "Target Sets CP template includes allowed-entry controls"
expect_fixed "targetSetAllowedSiteIds" "$TARGET_SETS_TEMPLATE" "Target Sets CP template includes allowed-site controls"
expect_fixed "id=\"targetSetCreateEditForm\"" "$TARGET_SETS_TEMPLATE" "Target Sets CP template renders a single create/edit form"
expect_absent "TARGET_SET_HANDLE=" "$TARGET_SETS_TEMPLATE" "Target Sets CP template no longer renders worker env helper content"
expect_absent "Helper Snippets" "$TARGET_SETS_TEMPLATE" "Target Sets CP template no longer renders helper snippets"
expect_pattern "<table class=\"data fullwidth big agents-target-sets-registry\"" "$TARGET_SETS_TEMPLATE" "Target Sets CP template renders a table-style registry"
expect_pattern "<th scope=\"col\"[^>]*>Name</th>" "$TARGET_SETS_TEMPLATE" "Target Sets CP template renders the Name column"
expect_pattern "<th scope=\"col\"[^>]*>Bounds</th>" "$TARGET_SETS_TEMPLATE" "Target Sets CP template renders the Bounds column"
expect_pattern "<th scope=\"col\"[^>]*>Used by</th>" "$TARGET_SETS_TEMPLATE" "Target Sets CP template renders the Used by column"
expect_pattern "<th scope=\"col\"[^>]*>Actions</th>" "$TARGET_SETS_TEMPLATE" "Target Sets CP template renders the Actions column"
expect_fixed "managed-account-ref" "$TARGET_SETS_TEMPLATE" "Target Sets CP template uses the shared managed-account reference in the Used by column"
expect_fixed "agents-page-shell" "$TARGET_SETS_TEMPLATE" "Target Sets CP template uses the shared page shell wrapper"
expect_fixed "{% include 'agents/_partials/cp-ui' %}" "$TARGET_SETS_TEMPLATE" "Target Sets CP template includes the shared CP UI wrapper styles"
expect_fixed "agents-table-toolbar" "$CP_TEMPLATE" "Credentials CP template uses the shared table toolbar wrapper"
expect_fixed "agents-table-attention-heading" "$CP_TEMPLATE" "Credentials CP template highlights the attention risk header"
expect_fixed "agents-table-attention-text" "$CP_TEMPLATE" "Credentials CP template highlights attention risk text"
expect_fixed "agents-account-templates-registry" "$CP_TEMPLATE" "Credentials CP template renders account templates as a table"
expect_fixed "{% set showAccountTemplateAccessColumn = writesExperimentalEnabled %}" "$CP_TEMPLATE" "Credentials CP template derives account-template access column visibility from the governed write flag"
expect_fixed "{% if showAccountTemplateAccessColumn %}" "$CP_TEMPLATE" "Credentials CP template conditionally renders the account-template Access column"
expect_pattern "<th scope=\"col\"[^>]*>Template</th>" "$CP_TEMPLATE" "Credentials CP template renders the Template column for account templates"
expect_pattern "<th scope=\"col\"[^>]*>Purpose</th>" "$CP_TEMPLATE" "Credentials CP template renders the Purpose column for account templates"
expect_pattern "<th scope=\"col\"[^>]*>Access</th>" "$CP_TEMPLATE" "Credentials CP template renders the Access column for account templates"
expect_fixed "var(--agents-table-body-padding-block)" "$CP_TEMPLATE" "Credentials CP template uses shared table body padding tokens"
expect_fixed "background: var(--secondary-pane-bg);" "$PLUGIN_ROOT/src/templates/_partials/cp-ui.twig" "Shared CP UI uses the restored strip background color"

echo "Credential lifecycle regression checks completed."
