#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

fail() {
  echo "FAIL: $1"
  exit 1
}

pass() {
  echo "PASS: $1"
}

expect_fixed() {
  local needle="$1"
  local file="$2"
  local description="$3"
  if grep -Fq -- "$needle" "$file"; then
    pass "$description"
    return
  fi
  fail "$description (missing: $needle in $file)"
}

expect_absent() {
  local needle="$1"
  local file="$2"
  local description="$3"
  if grep -Fq -- "$needle" "$file"; then
    fail "$description (unexpected: $needle in $file)"
  fi
  pass "$description"
}

PLUGIN_FILE="$PLUGIN_ROOT/src/Plugin.php"
DASHBOARD_CONTROLLER="$PLUGIN_ROOT/src/controllers/DashboardController.php"
WORKFLOW_SERVICE="$PLUGIN_ROOT/src/services/WorkflowService.php"
WORKFLOW_TEMPLATE="$PLUGIN_ROOT/src/templates/workflows.twig"
WORKFLOW_MIGRATION="$PLUGIN_ROOT/src/migrations/m260322_120000_add_workflows_tables.php"
WORKFLOW_NULLABLE_TARGET_SET_MIGRATION="$PLUGIN_ROOT/src/migrations/m260322_141500_make_workflow_target_set_nullable.php"
CP_DOCS="$PLUGIN_ROOT/docs/cp/index.md"
CP_UI_PARTIAL="$PLUGIN_ROOT/src/templates/_partials/cp-ui.twig"
MANAGED_ACCOUNT_PARTIAL="$PLUGIN_ROOT/src/templates/_partials/managed-account-ref.twig"

expect_fixed "PERMISSION_WORKFLOWS_VIEW" "$PLUGIN_FILE" "Plugin defines workflow view permission"
expect_fixed "PERMISSION_WORKFLOWS_MANAGE" "$PLUGIN_FILE" "Plugin defines workflow manage permission"
expect_fixed "'workflows' => [" "$PLUGIN_FILE" "Plugin registers Workflows subnav"
expect_fixed "'agents/workflows' => 'agents/dashboard/workflows'" "$PLUGIN_FILE" "Plugin registers workflows CP route"
expect_fixed "'agents/workflows/<workflowId:\\\\d+>' => 'agents/dashboard/workflows'" "$PLUGIN_FILE" "Plugin registers workflow detail CP route"

expect_fixed "class WorkflowService extends Component" "$WORKFLOW_SERVICE" "Workflow service class exists"
expect_fixed "getWorkflowTemplates" "$WORKFLOW_SERVICE" "Workflow service exposes template definitions"
expect_fixed "getWorkflows" "$WORKFLOW_SERVICE" "Workflow service exposes workflow registry"
expect_fixed "getWorkflowRuns" "$WORKFLOW_SERVICE" "Workflow service exposes run history lookup"
expect_fixed "getRuntimeWorkflowsForCredential" "$WORKFLOW_SERVICE" "Workflow service exposes runtime workflow discovery"
expect_fixed "getRuntimeWorkflowById" "$WORKFLOW_SERVICE" "Workflow service exposes runtime workflow detail lookup"
expect_fixed "reportWorkflowRun" "$WORKFLOW_SERVICE" "Workflow service exposes workflow run reporting"
expect_fixed "validateEntryIds" "$WORKFLOW_SERVICE" "Workflow service validates explicit workflow entry boundaries"
expect_fixed "validateProductIds" "$WORKFLOW_SERVICE" "Workflow service validates explicit workflow product boundaries"
expect_fixed "getAccountScopeCoverageByCredentialId" "$WORKFLOW_SERVICE" "Workflow service exposes account-to-workflow scope coverage summaries"
expect_fixed "evaluateWorkflowAccountScopeCoverage" "$WORKFLOW_SERVICE" "Workflow service evaluates whether an account is broader than a workflow"
expect_fixed "buildWorkflowAttentionState" "$WORKFLOW_SERVICE" "Workflow service derives workflow attention summaries for the CP"
expect_fixed "attentionSummary" "$WORKFLOW_SERVICE" "Workflow service exposes workflow attention summary text"
expect_fixed "attentionMeta" "$WORKFLOW_SERVICE" "Workflow service exposes workflow attention detail text"
expect_fixed "buildBootstrapBundleFiles" "$WORKFLOW_SERVICE" "Workflow service exposes bootstrap bundle generation"
expect_fixed "buildBundleReadme(array \$workflow, array \$template, string \$workflowSlug)" "$WORKFLOW_SERVICE" "Workflow service passes workflow slug explicitly into bundle README generation"
expect_fixed "return <<<'BASH'" "$WORKFLOW_SERVICE" "Workflow service keeps bundle run script shell variables literal via nowdoc"
expect_fixed "buildOutputContract" "$WORKFLOW_SERVICE" "Workflow service includes explicit workflow output-contract guidance"
expect_fixed "output-contract.md" "$WORKFLOW_SERVICE" "Workflow service bundles an output-contract file"
expect_fixed "WORKFLOW_DISCOVERY_PATH=/workflows" "$WORKFLOW_SERVICE" "Workflow service bundles the workflow discovery path"
expect_fixed "WORKFLOW_DETAIL_PATH=/workflows/show" "$WORKFLOW_SERVICE" "Workflow service bundles the workflow detail path"
expect_fixed "WORKFLOW_REPORT_PATH=/workflows/run-report" "$WORKFLOW_SERVICE" "Workflow service bundles the workflow report path"
expect_fixed "content-quality-review" "$WORKFLOW_SERVICE" "Workflow service includes the content quality review template"
expect_fixed "legal-consent-review" "$WORKFLOW_SERVICE" "Workflow service includes the legal and consent review template"
expect_fixed "change-monitor" "$WORKFLOW_SERVICE" "Workflow service includes the change monitor template"
expect_fixed "launch-readiness-review" "$WORKFLOW_SERVICE" "Workflow service includes the launch readiness review template"
expect_fixed "'mode' => 'read-only'" "$WORKFLOW_SERVICE" "Workflow service marks managed templates as read-only"

expect_fixed "agents_workflows" "$WORKFLOW_MIGRATION" "Workflow migration defines workflows table"
expect_fixed "agents_workflow_runs" "$WORKFLOW_MIGRATION" "Workflow migration defines workflow runs table"
expect_fixed "make_workflow_target_set_nullable" "$WORKFLOW_NULLABLE_TARGET_SET_MIGRATION" "Workflow nullable target-set migration exists"

expect_fixed "actionWorkflows" "$DASHBOARD_CONTROLLER" "Dashboard controller exposes workflows page"
expect_fixed "actionCreateWorkflow" "$DASHBOARD_CONTROLLER" "Dashboard controller supports workflow creation"
expect_fixed "actionUpdateWorkflow" "$DASHBOARD_CONTROLLER" "Dashboard controller supports workflow updates"
expect_fixed "actionPauseWorkflow" "$DASHBOARD_CONTROLLER" "Dashboard controller supports workflow pause"
expect_fixed "actionResumeWorkflow" "$DASHBOARD_CONTROLLER" "Dashboard controller supports workflow resume"
expect_fixed "actionDuplicateWorkflow" "$DASHBOARD_CONTROLLER" "Dashboard controller supports workflow duplication"
expect_fixed "actionDeleteWorkflow" "$DASHBOARD_CONTROLLER" "Dashboard controller supports workflow deletion"
expect_fixed "actionDownloadWorkflowBundle" "$DASHBOARD_CONTROLLER" "Dashboard controller supports workflow bundle download"
expect_fixed "sendBundleArchive" "$DASHBOARD_CONTROLLER" "Dashboard controller centralizes workflow handoff archive delivery"
expect_fixed "buildWorkflowPayloadFromRequest" "$DASHBOARD_CONTROLLER" "Dashboard controller builds workflow payloads from POST data"
expect_fixed "buildAvailableWorkflowAccounts" "$DASHBOARD_CONTROLLER" "Dashboard controller exposes eligible workflow accounts"
expect_fixed "workflowAccountSatisfiesRequiredScope" "$DASHBOARD_CONTROLLER" "Dashboard controller normalizes workflow account scope eligibility"
expect_fixed "missingScopes" "$DASHBOARD_CONTROLLER" "Dashboard controller surfaces missing workflow scopes for CP selection context"
expect_fixed "selectedCreateTemplate" "$DASHBOARD_CONTROLLER" "Dashboard controller tracks the selected workflow template in create mode"
expect_fixed "workflowEntryIds" "$DASHBOARD_CONTROLLER" "Dashboard controller accepts explicit workflow entry boundary selectors"
expect_fixed "workflowProductIds" "$DASHBOARD_CONTROLLER" "Dashboard controller accepts explicit workflow product boundary selectors"

expect_fixed "'agents/v1/workflows' => 'agents/api/workflows'" "$PLUGIN_FILE" "Plugin registers the workflow discovery API route"
expect_fixed "'agents/v1/workflows/show' => 'agents/api/workflow-show'" "$PLUGIN_FILE" "Plugin registers the workflow detail API route"
expect_fixed "'agents/v1/workflows/run-report' => 'agents/api/workflow-run-report'" "$PLUGIN_FILE" "Plugin registers the workflow run-report API route"

API_CONTROLLER="$PLUGIN_ROOT/src/controllers/ApiController.php"
SECURITY_POLICY_SERVICE="$PLUGIN_ROOT/src/services/SecurityPolicyService.php"

expect_fixed "actionWorkflows" "$API_CONTROLLER" "API controller exposes workflow discovery"
expect_fixed "actionWorkflowShow" "$API_CONTROLLER" "API controller exposes workflow detail"
expect_fixed "actionWorkflowRunReport" "$API_CONTROLLER" "API controller exposes workflow run reporting"
expect_fixed "requireManagedWorkflowCredentialId" "$API_CONTROLLER" "API controller requires managed workflow credentials for workflow runtime endpoints"
expect_fixed "'/workflows'" "$API_CONTROLLER" "API controller includes the workflow discovery path in OpenAPI"
expect_fixed "'/workflows/show'" "$API_CONTROLLER" "API controller includes the workflow detail path in OpenAPI"
expect_fixed "'/workflows/run-report'" "$API_CONTROLLER" "API controller includes the workflow report path in OpenAPI"
expect_fixed "'workflows:read'" "$API_CONTROLLER" "API controller exposes the workflow read scope"
expect_fixed "'workflows:report'" "$API_CONTROLLER" "API controller exposes the workflow report scope"

expect_fixed "'workflows:read'" "$SECURITY_POLICY_SERVICE" "Security policy includes the workflow read scope"
expect_fixed "'workflows:report'" "$SECURITY_POLICY_SERVICE" "Security policy includes the workflow report scope"

expect_fixed "selectedSubnavItem = 'workflows'" "$WORKFLOW_TEMPLATE" "Workflow template selects the workflows subnav item"
expect_fixed "{% set showWorkflowRiskColumn = workflowListFilter == 'attention' %}" "$WORKFLOW_TEMPLATE" "Workflow template gates the workflow risk column behind the attention filter"
expect_fixed "Create Workflow" "$WORKFLOW_TEMPLATE" "Workflow template exposes create workflow copy"
expect_fixed "Workflow configuration" "$WORKFLOW_TEMPLATE" "Workflow template exposes workflow edit copy"
expect_fixed "Handoff" "$WORKFLOW_TEMPLATE" "Workflow template exposes workflow handoff actions"
expect_fixed "Worker / Agent Handoff" "$WORKFLOW_TEMPLATE" "Workflow template labels the workflow handoff surface clearly"
expect_fixed "Recent runs" "$WORKFLOW_TEMPLATE" "Workflow template exposes recent run visibility"
expect_fixed "External execution" "$WORKFLOW_TEMPLATE" "Workflow template explains the external execution boundary"
expect_fixed "agents-workflows-registry" "$WORKFLOW_TEMPLATE" "Workflow template renders a registry table"
expect_fixed "agents-workflows-registry__col--icon" "$WORKFLOW_TEMPLATE" "Workflow template renders the leading workflow icon column"
expect_fixed "agents-workflows-registry-icon" "$WORKFLOW_TEMPLATE" "Workflow template renders the leading workflow icon in registry rows"
expect_fixed "agents-standard-registry-wrap" "$WORKFLOW_TEMPLATE" "Workflow template uses the shared standard registry wrapper"
expect_fixed "agents-standard-registry__header-cell" "$WORKFLOW_TEMPLATE" "Workflow template uses shared registry header cells"
expect_fixed "agents-standard-registry__body-cell--empty" "$WORKFLOW_TEMPLATE" "Workflow template uses shared empty-row registry styling"
expect_fixed "agents-table-attention-heading" "$WORKFLOW_TEMPLATE" "Workflow template highlights the attention risk header"
expect_fixed "agents-table-attention-text" "$WORKFLOW_TEMPLATE" "Workflow template highlights workflow attention reasons"
expect_fixed "missing:" "$WORKFLOW_TEMPLATE" "Workflow template explains account eligibility gaps in the account selector"
expect_fixed "agents-workflow-types-panel" "$WORKFLOW_TEMPLATE" "Workflow template renders a workflow-type library section"
expect_fixed "Workflow Types" "$WORKFLOW_TEMPLATE" "Workflow template labels the workflow-type library clearly"
expect_fixed "Use this type" "$WORKFLOW_TEMPLATE" "Workflow template exposes direct workflow-type actions"
expect_fixed "supported read-only workflow type" "$WORKFLOW_TEMPLATE" "Workflow template explains the read-only-first creation model"
expect_fixed "Workflow type" "$WORKFLOW_TEMPLATE" "Workflow template uses workflow-type language in the UI"
expect_fixed "types stay curated" "$WORKFLOW_TEMPLATE" "Workflow template explains why workflow types stay curated"
expect_absent "agents-workflow-template-library" "$WORKFLOW_TEMPLATE" "Workflow template no longer renders the old card picker library"
expect_absent "agents-workflow-template-card" "$WORKFLOW_TEMPLATE" "Workflow template no longer renders the old workflow template cards"
expect_fixed "No matching account yet" "$WORKFLOW_TEMPLATE" "Workflow template explains when no eligible workflow account exists"
expect_fixed "Create matching account in Accounts" "$WORKFLOW_TEMPLATE" "Workflow template hands missing-account setup off to Accounts"
expect_fixed 'type="time"' "$WORKFLOW_TEMPLATE" "Workflow template uses a plain HTML time input for schedule editing"
expect_absent "workflowTimezone" "$WORKFLOW_TEMPLATE" "Workflow template no longer exposes a timezone field"
expect_absent "workflowPausedFilterUrl" "$WORKFLOW_TEMPLATE" "Workflow template no longer exposes a paused filter in the toolbar"
expect_fixed "agents-table-toolbar" "$WORKFLOW_TEMPLATE" "Workflow template uses the shared table toolbar wrapper"
expect_fixed "getEntries()->getAllSections()" "$WORKFLOW_SERVICE" "Workflow service validates sections via Craft entries service"
expect_fixed "entries:write'" "$WORKFLOW_SERVICE" "Workflow service honors the deprecated draft-write scope alias"
expect_fixed "download the matching account handoff" "$WORKFLOW_SERVICE" "Workflow handoff guidance points operators back to the account handoff for secrets"
expect_fixed "cron example assumes the host already runs in the intended server/runtime timezone" "$WORKFLOW_SERVICE" "Workflow handoff guidance explains timezone handling as a host concern"
expect_fixed "OUTPUT_ROOT=" "$WORKFLOW_SERVICE" "Workflow handoff env examples include an output root"
expect_fixed "Download handoff" "$WORKFLOW_TEMPLATE" "Workflow template exposes workflow handoff download controls"
expect_fixed "label: 'Entries'" "$WORKFLOW_TEMPLATE" "Workflow template exposes entry relation pickers for workflow boundaries"
expect_fixed "elementType: 'craft\\\\elements\\\\Entry'" "$WORKFLOW_TEMPLATE" "Workflow template uses Craft's native entry element picker"
expect_fixed "label: 'Products'" "$WORKFLOW_TEMPLATE" "Workflow template exposes product relation pickers for workflow boundaries"
expect_fixed "workflowProductElementType" "$WORKFLOW_TEMPLATE" "Workflow template gates the product relation picker behind the Commerce element type"
expect_fixed "No runs yet. This workflow stores run history after an external runtime discovers due work and reports run lifecycle events through the workflow API." "$WORKFLOW_TEMPLATE" "Workflow template explains how run history is reported"
expect_fixed "Account fit:" "$WORKFLOW_TEMPLATE" "Workflow template exposes account fit for the bound workflow"
expect_fixed "Broader than this workflow" "$WORKFLOW_TEMPLATE" "Workflow template warns when a bound account is broader than the workflow"
expect_fixed "var(--ui-control-height)" "$CP_UI_PARTIAL" "Shared CP UI aligns the reusable filter strip to Craft control height"
expect_fixed "--agents-table-body-padding-block: 24px;" "$CP_UI_PARTIAL" "Shared CP UI defines reusable table body padding tokens"
expect_fixed "--agents-table-attention-color:" "$CP_UI_PARTIAL" "Shared CP UI defines reusable attention color tokens"
expect_fixed "background: var(--secondary-pane-bg);" "$CP_UI_PARTIAL" "Shared CP UI uses the restored strip background color"
expect_fixed "agents-managed-account-ref" "$CP_UI_PARTIAL" "Shared CP UI styles the reusable managed-account reference"
expect_fixed "color: #596673;" "$CP_UI_PARTIAL" "Shared CP UI keeps the managed-account reference label muted"
expect_fixed "font-weight: 700;" "$CP_UI_PARTIAL" "Shared CP UI keeps the managed-account reference label bold"
expect_fixed "managed-account-ref" "$WORKFLOW_TEMPLATE" "Workflow template uses the shared managed-account reference partial"
expect_fixed "managed-account-ref" "$MANAGED_ACCOUNT_PARTIAL" "Managed-account reference partial exists"
expect_absent "<a href=" "$MANAGED_ACCOUNT_PARTIAL" "Managed-account reference partial no longer links to the account surface"

expect_fixed "**Workflows**" "$CP_DOCS" "CP docs include the Workflows surface"
expect_fixed "admin/agents/workflows" "$CP_DOCS" "CP docs include the workflows route"
expect_fixed "read-only workflow instances" "$CP_DOCS" "CP docs describe workflows as read-only"
expect_fixed "handoff bundle" "$CP_DOCS" "CP docs mention workflow handoff bundles"
expect_fixed "job runner" "$CP_DOCS" "CP docs explain that Agents is not the workflow job runner"
expect_fixed "recent-run visibility backed by the workflow polling and run-reporting contract" "$CP_DOCS" "CP docs explain the intentional workflow run reporting model"
expect_fixed 'Latest Run` and `Recent runs` are populated when the bound runtime reports lifecycle state through the workflow API' "$CP_DOCS" "CP docs explain how workflow run visibility is populated"
expect_fixed "workflow-type-based creation" "$CP_DOCS" "CP docs frame workflow creation around workflow types"

pass "Workflow feature regression checks completed"
